profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "g3rs-clippy-config-checks",
  "g3rs-clippy-ingestion",
  "g3rs-code-ingestion",
  "g3rs-code-source-checks",
  "g3rs-hooks-config-checks",
  "g3rs-hooks-config-checks-types",
  "g3rs-hooks-file-tree-checks",
  "g3rs-hooks-file-tree-checks-types",
  "g3rs-hooks-source-checks",
  "g3rs-hooks-types",
  "g3-workspace-crawl",
  "guardrail3-check-types",
  "hook-shell-parser",
  "tempfile",
]

[checks]
hooks = false
