#![expect(
    clippy::arithmetic_side_effects,
    reason = "managed hook block insertion operates on byte offsets returned by marker search"
)]
#![expect(
    clippy::disallowed_methods,
    reason = "init is the centralized writer for repo and workspace guardrail files"
)]
#![expect(
    clippy::indexing_slicing,
    reason = "managed hook block insertion uses bounded line indexes"
)]
#![allow(
    clippy::missing_docs_in_private_items,
    reason = "private init helpers are implementation details of the CLI init command"
)]
#![expect(
    clippy::string_slice,
    reason = "managed hook marker offsets are ASCII marker boundaries returned from str::find"
)]

use std::fmt::Write as _;
use std::path::Path;
use std::process::{Command, Stdio};

use guardrail3_rs_app_types::{InitRepoRequest, InitWorkspaceRequest};

use crate::fs as local_fs;
use crate::{outcome::ExecutionOutcome, staged::resolve_repo_root};

const GENERATED_HEADER: &str = "# Generated by g3rs. Do not edit this file directly.";
const BEGIN_MARKER: &str = "# g3rs:begin managed repo guardrails";
const END_MARKER: &str = "# g3rs:end managed repo guardrails";
const MANAGED_HOOK_REL: &str = ".githooks/pre-commit.d/g3rs";

/// Executes repo initialization.
#[must_use]
pub fn execute_init_repo(request: &InitRepoRequest) -> ExecutionOutcome {
    let repo_root = resolve_repo_root(&request.path);
    let hooks_dir = repo_root.join(".githooks");
    let managed_dir = hooks_dir.join("pre-commit.d");
    let pre_commit = hooks_dir.join("pre-commit");
    let managed_hook = repo_root.join(MANAGED_HOOK_REL);

    let mut changes = Vec::new();
    let mut refusals = Vec::new();

    if create_dir(&hooks_dir, ".githooks", &mut changes, &mut refusals).is_err()
        || create_dir(
            &managed_dir,
            ".githooks/pre-commit.d",
            &mut changes,
            &mut refusals,
        )
        .is_err()
    {
        return refusal_outcome(&refusals);
    }

    write_managed_file(
        &managed_hook,
        &managed_g3rs_hook(),
        MANAGED_HOOK_REL,
        request.force,
        &mut changes,
        &mut refusals,
    );

    if refusals.is_empty() {
        make_executable(&managed_hook);
    }

    if pre_commit.exists() {
        integrate_pre_commit(&pre_commit, request.force, &mut changes, &mut refusals);
    } else {
        write_new_file(
            &pre_commit,
            &managed_pre_commit_adapter(),
            ".githooks/pre-commit",
            &mut changes,
            &mut refusals,
        );
        if refusals.is_empty() {
            make_executable(&pre_commit);
        }
    }

    if !refusals.is_empty() {
        return refusal_outcome(&refusals);
    }

    configure_hooks_path(&repo_root, &mut changes);

    let mut stdout = if changes.is_empty() {
        "repo already initialized\n".to_owned()
    } else {
        let mut lines = vec!["initialized repo".to_owned()];
        lines.extend(changes);
        format!("{}\n", lines.join("\n"))
    };
    let _ = writeln!(
        stdout,
        "validate with: g3rs validate repo --path {}",
        repo_root.display()
    );
    ExecutionOutcome::new(stdout, String::new(), 0)
}

/// Executes workspace initialization.
#[must_use]
pub fn execute_init_workspace(request: &InitWorkspaceRequest) -> ExecutionOutcome {
    let root = request.workspace_root.clone();
    if !root.join("Cargo.toml").is_file() {
        return ExecutionOutcome::new(
            String::new(),
            format!("path has no Cargo.toml: {}\n", root.display()),
            1,
        );
    }

    let mut changes = Vec::new();
    let mut refusals = Vec::new();
    let guardrail_config = root.join("guardrail3-rs.toml");
    if !guardrail_config.exists() {
        write_new_file(
            &guardrail_config,
            "profile = \"library\"\n",
            "guardrail3-rs.toml",
            &mut changes,
            &mut refusals,
        );
    }

    if !refusals.is_empty() {
        return refusal_outcome(&refusals);
    }

    let mut stdout = if changes.is_empty() {
        "workspace already initialized\n".to_owned()
    } else {
        let mut lines = vec!["initialized workspace".to_owned()];
        lines.extend(changes);
        format!("{}\n", lines.join("\n"))
    };
    let _ = writeln!(
        stdout,
        "validate with: g3rs validate workspace --path {}",
        root.display()
    );
    ExecutionOutcome::new(stdout, String::new(), 0)
}

fn create_dir(
    path: &Path,
    rel: &str,
    changes: &mut Vec<String>,
    refusals: &mut Vec<String>,
) -> std::io::Result<()> {
    if path.exists() {
        return Ok(());
    }
    match local_fs::create_dir_all(path) {
        Ok(()) => {
            changes.push(format!("created {rel}"));
            Ok(())
        }
        Err(error) => {
            refusals.push(format!("refused to create {rel}\nreason: {error}"));
            Err(error)
        }
    }
}

fn write_new_file(
    path: &Path,
    content: &str,
    rel: &str,
    changes: &mut Vec<String>,
    refusals: &mut Vec<String>,
) {
    if path.exists() {
        return;
    }
    match local_fs::write(path, content) {
        Ok(()) => changes.push(format!("created {rel}")),
        Err(error) => refusals.push(format!("refused to write {rel}\nreason: {error}")),
    }
}

fn write_managed_file(
    path: &Path,
    content: &str,
    rel: &str,
    force: bool,
    changes: &mut Vec<String>,
    refusals: &mut Vec<String>,
) {
    match local_fs::read_to_string(path) {
        Ok(existing) if existing == content => {}
        Ok(existing)
            if existing.starts_with(GENERATED_HEADER) || existing.contains(GENERATED_HEADER) =>
        {
            if force {
                if let Err(error) = local_fs::write(path, content) {
                    refusals.push(format!("refused to rewrite {rel}\nreason: {error}"));
                } else {
                    changes.push(format!("updated {rel}"));
                }
            } else {
                refusals.push(format!(
                    "refused to modify {rel}\nreason: generated file differs; rerun with --force"
                ));
            }
        }
        Ok(_) => refusals.push(format!(
            "refused to modify {rel}\nreason: project-owned file is not managed by G3RS"
        )),
        Err(read_error) if read_error.kind() == std::io::ErrorKind::NotFound => {
            if let Err(write_error) = local_fs::write(path, content) {
                refusals.push(format!("refused to write {rel}\nreason: {write_error}"));
            } else {
                changes.push(format!("created {rel}"));
            }
        }
        Err(error) => refusals.push(format!("refused to read {rel}\nreason: {error}")),
    }
}

fn integrate_pre_commit(
    path: &Path,
    force: bool,
    changes: &mut Vec<String>,
    refusals: &mut Vec<String>,
) {
    let rel = ".githooks/pre-commit";
    let Ok(existing) = local_fs::read_to_string(path) else {
        refusals.push(format!(
            "refused to modify {rel}\nreason: file is not valid UTF-8 text"
        ));
        return;
    };
    if existing == managed_pre_commit_adapter() {
        return;
    }
    if existing.starts_with(GENERATED_HEADER) {
        if force {
            if let Err(error) = local_fs::write(path, &managed_pre_commit_adapter()) {
                refusals.push(format!("refused to rewrite {rel}\nreason: {error}"));
            } else {
                changes.push(format!("updated {rel}"));
            }
            return;
        }
        refusals.push(format!(
            "refused to modify {rel}\nreason: generated file differs; rerun with --force"
        ));
        return;
    }
    if !force {
        refusals.push(format!(
            "refused to modify {rel}\nreason: project-owned hook needs explicit managed-block insertion\nrerun with --force to insert the G3RS managed block"
        ));
        return;
    }
    if unsupported_interpreter(&existing) {
        refusals.push(format!(
            "refused to modify {rel}\nreason: unsupported hook interpreter"
        ));
        return;
    }
    match insert_or_replace_block(&existing) {
        Ok(updated) => {
            if updated != existing {
                if let Err(error) = local_fs::write(path, &updated) {
                    refusals.push(format!("refused to modify {rel}\nreason: {error}"));
                } else {
                    changes.push(format!("updated {rel}"));
                }
            }
        }
        Err(reason) => refusals.push(format!("refused to modify {rel}\nreason: {reason}")),
    }
}

fn unsupported_interpreter(content: &str) -> bool {
    let Some(first) = content.lines().next() else {
        return false;
    };
    first.starts_with("#!") && !first.contains("sh") && !first.contains("bash")
}

fn insert_or_replace_block(content: &str) -> Result<String, &'static str> {
    let begin_count = content.matches(BEGIN_MARKER).count();
    let end_count = content.matches(END_MARKER).count();
    if begin_count > 1 || end_count > 1 || begin_count != end_count {
        return Err("duplicate or unbalanced G3RS managed blocks");
    }
    let block = managed_block();
    if begin_count == 1 {
        let Some(begin) = content.find(BEGIN_MARKER) else {
            return Err("managed block begin marker missing");
        };
        let Some(end_start) = content.find(END_MARKER) else {
            return Err("managed block end marker missing");
        };
        let end = end_start + END_MARKER.len();
        let mut updated = String::new();
        updated.push_str(&content[..begin]);
        updated.push_str(block.as_str());
        updated.push_str(&content[end..]);
        return Ok(updated);
    }

    let mut lines = content.lines().collect::<Vec<_>>();
    let trailing_newline = content.ends_with('\n');
    let mut insert_at = 0;
    if lines.first().is_some_and(|line| line.starts_with("#!")) {
        insert_at = 1;
        while insert_at < lines.len() && lines[insert_at].trim_start().starts_with("set ") {
            insert_at += 1;
        }
    }
    lines.insert(insert_at, block.trim_end());
    let mut updated = lines.join("\n");
    if trailing_newline {
        updated.push('\n');
    }
    Ok(updated)
}

fn managed_pre_commit_adapter() -> String {
    format!(
        "#!/usr/bin/env bash\nset -euo pipefail\n{GENERATED_HEADER}\n\n{}",
        managed_block()
    )
}

fn managed_block() -> String {
    format!(
        "{BEGIN_MARKER}\nrepo_root=\"$(git rev-parse --show-toplevel)\"\ncd \"$repo_root\"\nif [ -x \"{MANAGED_HOOK_REL}\" ]; then\n    . \"{MANAGED_HOOK_REL}\"\nelse\n    echo \"ERROR: missing executable {MANAGED_HOOK_REL}\"\n    exit 1\nfi\n{END_MARKER}\n"
    )
}

#[expect(
    clippy::too_many_lines,
    reason = "managed hook template is kept contiguous so generated shell content is reviewable"
)]
fn managed_g3rs_hook() -> String {
    format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
{GENERATED_HEADER}

repo_root="$(git rev-parse --show-toplevel)"
export CARGO_TARGET_DIR="$repo_root/.cargo-target"

staged_files=$(git diff --cached --name-only --diff-filter=ACM)
validation_staged_files=$(printf '%s\n' "$staged_files" | grep -vE '^behavior/fixtures/' || true)

while IFS= read -r file; do
    [ -n "$file" ] || continue
    [ -f "$repo_root/$file" ] || continue
    if grep -qE '^(<{{7}} |={{7}}$|>{{7}} )' "$repo_root/$file" 2>/dev/null; then
        echo "Merge conflict markers found in $file"
        exit 1
    fi
done <<< "$staged_files"

if ! command -v gitleaks >/dev/null 2>&1; then
    echo "ERROR: gitleaks not installed. Install: brew install gitleaks"
    exit 1
fi
if ! gitleaks protect --staged --no-banner; then
    echo "Secret detected in staged files. Remove it before committing."
    exit 1
fi

max_file_size=1048576
while IFS= read -r file; do
    [ -n "$file" ] || continue
    if git cat-file -e ":$file" 2>/dev/null; then
        file_size=$(git cat-file -s ":$file")
        if [ "$file_size" -gt "$max_file_size" ]; then
            echo "File $file is too large (${{file_size}} bytes, max ${{max_file_size}})."
            exit 1
        fi
    fi
done <<< "$staged_files"

g3rs validate repo --path "$repo_root"

find_owning_unit() {{
    local start_dir="$1"
    local dir="$start_dir"
    while :; do
        if [ -f "$dir/Cargo.toml" ] && [ -f "$dir/guardrail3-rs.toml" ]; then
            echo "$dir"
            return 0
        fi
        if [ "$dir" = "$repo_root" ] || [ "$dir" = "/" ] || [ -z "$dir" ]; then
            return 1
        fi
        dir=$(dirname "$dir")
    done
}}

staged_file_dir() {{
    local rel="$1"
    local dir
    dir=$(dirname "$rel")
    if [ "$dir" = "." ] || [ -z "$dir" ]; then
        echo "$repo_root"
    else
        echo "$repo_root/$dir"
    fi
}}

rust_relevant_pattern='(\.rs$|(^|/)Cargo\.toml$|(^|/)Cargo\.lock$|(^|/)rust-toolchain$|(^|/)rust-toolchain\.toml$|(^|/)rustfmt\.toml$|(^|/)\.rustfmt\.toml$|(^|/)clippy\.toml$|(^|/)\.clippy\.toml$|(^|/)deny\.toml$|(^|/)\.deny\.toml$|(^|/)guardrail3-rs\.toml$|(^|/)\.cargo/config$|(^|/)\.cargo/config\.toml$)'
rust_relevant_files=$(echo "$validation_staged_files" | grep -E "$rust_relevant_pattern" || true)

rust_owning_units=""
if [ -n "$rust_relevant_files" ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        start_dir=$(staged_file_dir "$file")
        if unit=$(find_owning_unit "$start_dir"); then
            rust_owning_units="${{rust_owning_units}}${{unit}}"$'\n'
        fi
    done <<< "$rust_relevant_files"
fi

rust_unique_units=$(printf '%s' "$rust_owning_units" | awk 'NF' | sort -u)

if [ -n "$rust_unique_units" ]; then
    while IFS= read -r unit; do
        [ -n "$unit" ] || continue
        g3rs validate workspace --path "$unit" --staged
    done <<< "$rust_unique_units"
fi
"#
    )
}

fn configure_hooks_path(repo_root: &Path, changes: &mut Vec<String>) {
    let output = Command::new("git")
        .args(["config", "--get", "core.hooksPath"])
        .current_dir(repo_root)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output();
    let current = output
        .ok()
        .filter(|out| out.status.success())
        .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_owned())
        .unwrap_or_default();
    if current == ".githooks" {
        return;
    }
    let status = Command::new("git")
        .args(["config", "core.hooksPath", ".githooks"])
        .current_dir(repo_root)
        .status();
    if status.is_ok_and(|status| status.success()) {
        changes.push("configured core.hooksPath=.githooks".to_owned());
    }
}

fn make_executable(path: &Path) {
    local_fs::make_executable(path);
}

fn refusal_outcome(refusals: &[String]) -> ExecutionOutcome {
    ExecutionOutcome::new(String::new(), format!("{}\n", refusals.join("\n")), 1)
}
