use std::fmt::Write;

use crate::Module;

use super::macros::MACRO_DEBUGGING;
use super::methods::{
    METHOD_GARDE_DESERIALIZATION, library_profile_methods, service_profile_methods,
};
use super::settings::SETTINGS;
use super::thresholds::THRESHOLDS;
use super::types::{TYPE_GARDE_EXTRACTORS, library_profile_types, service_profile_types};

/// Build the full clippy.toml content for a workspace root or crate.
///
/// `_is_pure_layer` is accepted for generator call-site compatibility but does not
/// change the managed clippy baseline. Pure-layer semantics belong to architecture
/// checks rather than clippy profile generation.
/// `extra_methods` and `extra_types` are appended from local override files.
pub fn build_clippy_toml(
    profile: &str,
    _is_pure_layer: bool,
    garde_enabled: bool,
    extra_methods: &str,
    extra_types: &str,
) -> String {
    let mut methods = match profile {
        "library" => library_profile_methods(),
        _ => service_profile_methods(),
    };
    if !garde_enabled {
        methods.retain(|module| module.name != METHOD_GARDE_DESERIALIZATION.name);
    }

    let mut types = match profile {
        "library" => library_profile_types(),
        _ => service_profile_types(),
    };
    if !garde_enabled {
        types.retain(|module| module.name != TYPE_GARDE_EXTRACTORS.name);
    }

    let mut out = String::new();
    out.push_str(
        "# =============================================================================\n",
    );
    let _ = writeln!(
        out,
        "# clippy.toml -- GENERATED by guardrail3 (profile: {profile})"
    );
    out.push_str("# DO NOT EDIT -- regenerate with: guardrail3 generate\n");
    out.push_str(
        "# =============================================================================\n\n",
    );

    out.push_str("# THRESHOLDS\n");
    out.push_str(THRESHOLDS);
    out.push_str("\n\n");
    out.push_str("# SETTINGS\n");
    out.push_str(SETTINGS);
    out.push_str("\n\n");

    render_module_array(
        &mut out,
        "DISALLOWED METHODS",
        "disallowed-methods",
        &methods,
        extra_methods,
    );
    out.push('\n');
    render_module_array(
        &mut out,
        "DISALLOWED TYPES",
        "disallowed-types",
        &types,
        extra_types,
    );
    out.push('\n');
    render_module_array(
        &mut out,
        "DISALLOWED MACROS",
        "disallowed-macros",
        &[&MACRO_DEBUGGING],
        "",
    );

    out
}

fn render_module_array(
    out: &mut String,
    header: &str,
    key: &str,
    modules: &[&Module],
    extra_entries: &str,
) {
    out.push_str("# ");
    out.push_str(header);
    out.push('\n');
    out.push_str(key);
    out.push_str(" = [\n");
    for module in modules {
        let _ = writeln!(out, "    # --- {} ---", module.description);
        out.push_str(module.content);
        out.push('\n');
    }
    let deduped = crate::deduplicated_override(out, extra_entries);
    if !deduped.trim().is_empty() {
        out.push_str("    # --- Local overrides ---\n");
        out.push_str(&deduped);
    }
    out.push_str("]\n");
}
