#[cfg(feature = "api")]
pub mod types;

#[cfg(feature = "api")]
pub type BadgeTable = types::BadgeTable;
#[cfg(feature = "api")]
pub type Badges = types::Badges;
#[cfg(feature = "api")]
pub type CargoToml = types::CargoToml;
#[cfg(feature = "api")]
pub type Dependency = types::Dependency;
#[cfg(feature = "api")]
pub type DependencyDetail = types::DependencyDetail;
#[cfg(feature = "api")]
pub type FeatureList = types::FeatureList;
#[cfg(feature = "api")]
pub type FeatureMap = types::FeatureMap;
#[cfg(feature = "api")]
pub type HintsConfig = types::HintsConfig;
#[cfg(feature = "api")]
pub type InheritableStrings = types::InheritableStrings;
#[cfg(feature = "api")]
pub type InheritableValue<T> = types::InheritableValue<T>;
#[cfg(feature = "api")]
pub type IntegerOrBool = types::IntegerOrBool;
#[cfg(feature = "api")]
pub type IntegerOrString = types::IntegerOrString;
#[cfg(feature = "api")]
pub type LintDetail = types::LintDetail;
#[cfg(feature = "api")]
pub type LintTools = types::LintTools;
#[cfg(feature = "api")]
pub type LintValue = types::LintValue;
#[cfg(feature = "api")]
pub type LintsConfig = types::LintsConfig;
#[cfg(feature = "api")]
pub type PackageBuildValue = types::PackageBuildValue;
#[cfg(feature = "api")]
pub type PackageSection = types::PackageSection;
#[cfg(feature = "api")]
pub type PatchRegistryTable = types::PatchRegistryTable;
#[cfg(feature = "api")]
pub type PatchTable = types::PatchTable;
#[cfg(feature = "api")]
pub type ProfileConfig = types::ProfileConfig;
#[cfg(feature = "api")]
pub type StringOrBool = types::StringOrBool;
#[cfg(feature = "api")]
pub type StringOrVec = types::StringOrVec;
#[cfg(feature = "api")]
pub type TargetDependencyTables = types::TargetDependencyTables;
#[cfg(feature = "api")]
pub type TargetSection = types::TargetSection;
#[cfg(feature = "api")]
pub type TomlTrimPaths = types::TomlTrimPaths;
#[cfg(feature = "api")]
pub type TomlTrimPathsValue = types::TomlTrimPathsValue;
#[cfg(feature = "api")]
pub type ToolLints = types::ToolLints;
#[cfg(feature = "api")]
pub type Value = types::Value;
#[cfg(feature = "api")]
pub type VecStringOrBool = types::VecStringOrBool;
#[cfg(feature = "api")]
pub type WorkspaceInheritance = types::WorkspaceInheritance;
#[cfg(feature = "api")]
pub type WorkspacePackageSection = types::WorkspacePackageSection;
#[cfg(feature = "api")]
pub type WorkspaceSection = types::WorkspaceSection;

#[cfg(feature = "api")]
pub use cargo_toml_parser_runtime::{Error, from_path, parse};
