profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "g3rs-fmt-config-checks",
  "g3rs-fmt-filetree-checks",
  "g3rs-fmt-ingestion-assertions",
  "g3rs-fmt-ingestion-runtime",
  "g3rs-fmt-ingestion-types",
  "g3rs-fmt-types",
  "g3-workspace-crawl",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "rust-toolchain-toml-parser",
  "rustfmt-toml-parser",
  "tempfile",
  "toml",
]

[checks]
garde = false
