//! Adversarial integration tests for corrupted, partial, and weird config files.
//!
//! These tests verify:
//! - Unknown app types fall back to service
//! - CRLF line endings detected as differences
//! - UTF-8 BOM handled gracefully
//! - Empty config files trigger updates
//! - BOM in override files stripped before processing
//! - Invalid override lines skipped with warnings
//! - Null bytes in overrides handled without crashes
//! - Unrecognized override files silently ignored
//! - `ts init --force` replaces [typescript] section while preserving [rust]

// Suppress unused crate dependency warnings for crates used only by the main binary
use clap as _;
use colored as _;
use garde as _;
use glob as _;
use guardrail3 as _;
use ignore as _;
use proc_macro2 as _;
use proptest as _;
use quote as _;
use semver as _;
use serde as _;
use serde_json as _;
use serde_yaml as _;
use std::process::Command;
use syn as _;
use toml as _;
use toml_edit as _;
use tree_sitter as _;
use tree_sitter_javascript as _;
use tree_sitter_typescript as _;
use walkdir as _;

#[allow(clippy::disallowed_methods)] // reason: Command::new needed to invoke binary under test
fn guardrail3() -> Command {
    Command::new(env!("CARGO_BIN_EXE_guardrail3"))
}

/// Canonical rustfmt.toml content (matches what guardrail3 generates).
const CANONICAL_RUSTFMT: &str = r#"# =============================================================================
# rustfmt configuration -- GENERATED by guardrail3
# DO NOT EDIT -- regenerate with: guardrail3 generate
# =============================================================================

# --- Stable settings (work with any rustfmt) ---------------------------------

edition = "2024"
max_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true

# --- Nightly-only settings ----------------------------------------------------
# These require nightly rustfmt: cargo +nightly fmt
# On stable rustfmt they will produce an error. Uncomment only if your
# CI/local workflow uses nightly rustfmt.
#
# Check compatibility with: rustfmt --version
# Nightly status tracking: https://rust-lang.github.io/rustfmt/

# imports_granularity = "Crate"           # Merge imports from the same crate into one `use` block
# group_imports = "StdExternalCrate"      # Three-tier ordering: std -> external crates -> internal modules
# format_code_in_doc_comments = true      # Run rustfmt on code blocks inside /// doc comments
# format_strings = true                   # Wrap long string literals
# overflow_delimited_expr = true          # Allow closures/arrays to overflow for readability
"#;

/// Set up the broken configs fixture directory.
#[allow(clippy::disallowed_methods)] // reason: test helper -- writes fixture files to temp dir
#[allow(clippy::expect_used)] // reason: test helper -- panics on write failure
fn setup_broken_configs(dir: &std::path::Path) {
    // Cargo.toml: workspace with a single crate
    std::fs::write(
        dir.join("Cargo.toml"),
        concat!(
            "[workspace]\n",
            "members = [\"crates/*\"]\n",
            "resolver = \"2\"\n",
        ),
    )
    .expect("write Cargo.toml");

    // crates/app/Cargo.toml
    std::fs::create_dir_all(dir.join("crates/app")).expect("create crates/app");
    std::fs::write(
        dir.join("crates/app/Cargo.toml"),
        "[package]\nname = \"broken-app\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write crates/app/Cargo.toml");

    // guardrail3.toml with unknown type "frontend"
    std::fs::write(
        dir.join("guardrail3.toml"),
        concat!(
            "version = \"0.1\"\n",
            "\n",
            "[profile]\n",
            "name = \"service\"\n",
            "\n",
            "[rust]\n",
            "workspace_root = \".\"\n",
            "\n",
            "[rust.apps.app]\n",
            "type = \"frontend\"\n",
        ),
    )
    .expect("write guardrail3.toml");

    // clippy.toml with CRLF line endings
    let crlf_content = CANONICAL_RUSTFMT.replace('\n', "\r\n");
    // Use this as a pre-existing clippy.toml to test CRLF detection
    // (we use rustfmt content as a stand-in -- it's the format difference that matters)
    std::fs::write(dir.join("clippy.toml"), crlf_content).expect("write CRLF clippy.toml");

    // deny.toml with UTF-8 BOM
    let bom_deny = format!(
        "\u{FEFF}{}",
        concat!(
            "[graph]\n",
            "all-features = true\n",
            "\n",
            "[bans]\n",
            "multiple-versions = \"warn\"\n",
            "deny = [\n",
            "    { name = \"openssl\", wrappers = [] },\n",
            "]\n",
        )
    );
    std::fs::write(dir.join("deny.toml"), bom_deny).expect("write BOM deny.toml");

    // rustfmt.toml: empty file (0 bytes)
    std::fs::write(dir.join("rustfmt.toml"), "").expect("write empty rustfmt.toml");

    // .guardrail3/overrides/ with various broken files
    let overrides_dir = dir.join(".guardrail3/overrides");
    std::fs::create_dir_all(&overrides_dir).expect("create overrides dir");

    // clippy-methods.toml with BOM + valid entry
    std::fs::write(
        overrides_dir.join("clippy-methods.toml"),
        "\u{FEFF}    { path = \"std::process::Command::new\", reason = \"Banned\" },\n",
    )
    .expect("write BOM clippy-methods.toml");

    // deny-bans.toml with mix: valid, invalid, null byte
    std::fs::write(
        overrides_dir.join("deny-bans.toml"),
        "    { name = \"custom-ban\", wrappers = [] },\nthis is not valid toml\n    { name = \"another-ban\0\", wrappers = [] },\n",
    )
    .expect("write mixed deny-bans.toml");

    // mystery-file.toml: unrecognized override name
    std::fs::write(
        overrides_dir.join("mystery-file.toml"),
        "    { path = \"mystery::function\", reason = \"should not appear\" },\n",
    )
    .expect("write mystery-file.toml");
}

// ---------------------------------------------------------------------------
// Test 1: unknown type "frontend" falls back to service profile
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn unknown_type_falls_back_to_service() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", "--dry-run", path_str])
        .output()
        .expect("failed to run");

    // Should not crash
    let stderr = String::from_utf8_lossy(&out.stderr);
    let stdout = String::from_utf8_lossy(&out.stdout);

    // Should show clippy.toml in output (service profile used as fallback)
    assert!(
        stdout.contains("clippy.toml"),
        "Diff output should mention clippy.toml (service fallback), got stdout:\n{stdout}\nstderr:\n{stderr}"
    );
}

// ---------------------------------------------------------------------------
// Test 2: CRLF clippy.toml detected as needing update
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn crlf_clippy_detected_as_update() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", "--dry-run", path_str])
        .output()
        .expect("failed to run");

    let stdout = String::from_utf8_lossy(&out.stdout);
    // The CRLF file should differ from the canonical LF-only content
    // It should show as "would update" or "would create" (since content differs)
    assert!(
        stdout.contains("clippy.toml")
            && (stdout.contains("would update") || stdout.contains("would create")),
        "CRLF clippy.toml should be detected as different, got:\n{stdout}"
    );
}

// ---------------------------------------------------------------------------
// Test 3: BOM deny.toml handled without crash
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn bom_deny_toml_handled() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", "--dry-run", path_str])
        .output()
        .expect("failed to run");

    let stdout = String::from_utf8_lossy(&out.stdout);
    // Should mention deny.toml (not crash)
    assert!(
        stdout.contains("deny.toml"),
        "Diff output should mention deny.toml (BOM handled), got:\n{stdout}"
    );
}

// ---------------------------------------------------------------------------
// Test 4: empty rustfmt.toml at app path shows "would create" in diff
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn empty_rustfmt_shows_would_create() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    // Also place an empty rustfmt.toml at the app path where generate will write
    std::fs::create_dir_all(dir.join("crates/app")).expect("create crates/app");
    std::fs::write(dir.join("crates/app/rustfmt.toml"), "").expect("write empty app rustfmt.toml");

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", "--dry-run", path_str])
        .output()
        .expect("failed to run");

    let stdout = String::from_utf8_lossy(&out.stdout);
    // The empty rustfmt.toml at the app path should show as "would update"
    assert!(
        stdout.contains("rustfmt.toml") && stdout.contains("would update"),
        "Empty rustfmt.toml should show 'would update', got:\n{stdout}"
    );
}

// ---------------------------------------------------------------------------
// Test 5: BOM in override file stripped, entry processed correctly
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn bom_in_override_stripped() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", path_str])
        .output()
        .expect("failed to run");

    assert!(
        out.status.success(),
        "generate should succeed: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // The BOM override had { path = "std::process::Command::new" }
    // This entry already exists in the service profile's process-control module,
    // so it will be deduplicated. Check that clippy.toml contains it at all
    // (from the base module, not necessarily from override).
    let clippy = std::fs::read_to_string(dir.join("crates/app/clippy.toml"))
        .or_else(|_| std::fs::read_to_string(dir.join("clippy.toml")))
        .expect("read generated clippy.toml");
    assert!(
        clippy.contains("std::process::Command::new"),
        "Generated clippy.toml should contain std::process::Command::new (from base or override), got:\n{clippy}"
    );
}

// ---------------------------------------------------------------------------
// Test 6: invalid override lines produce stderr warnings
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn invalid_override_line_skipped_with_warning() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", path_str])
        .output()
        .expect("failed to run");

    let stderr = String::from_utf8_lossy(&out.stderr);
    // The "this is not valid toml" line should trigger a warning
    assert!(
        stderr.contains("skipping invalid line"),
        "Should warn about invalid override line, stderr was:\n{stderr}"
    );
}

// ---------------------------------------------------------------------------
// Test 7: null byte in override handled without crash
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn null_byte_in_override_handled() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", path_str])
        .output()
        .expect("failed to run");

    // Should not crash -- generate should succeed (possibly with warnings)
    assert!(
        out.status.success(),
        "generate should not crash on null bytes, stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

// ---------------------------------------------------------------------------
// Test 8: unrecognized override file silently ignored
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn unrecognized_override_file_silently_ignored() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();
    setup_broken_configs(dir);

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["rs", "generate", path_str])
        .output()
        .expect("failed to run");

    assert!(
        out.status.success(),
        "generate should succeed: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // mystery-file.toml content should NOT appear in any generated file
    let clippy = std::fs::read_to_string(dir.join("crates/app/clippy.toml"))
        .or_else(|_| std::fs::read_to_string(dir.join("clippy.toml")))
        .expect("read generated clippy.toml");
    assert!(
        !clippy.contains("mystery::function"),
        "mystery-file.toml content should not appear in clippy.toml, got:\n{clippy}"
    );

    let deny = std::fs::read_to_string(dir.join("crates/app/deny.toml"))
        .or_else(|_| std::fs::read_to_string(dir.join("deny.toml")))
        .expect("read generated deny.toml");
    assert!(
        !deny.contains("mystery::function"),
        "mystery-file.toml content should not appear in deny.toml"
    );
}

// ---------------------------------------------------------------------------
// Test 9: ts init --force removes old [typescript] subsections, preserves [rust]
// ---------------------------------------------------------------------------

#[test]
#[allow(clippy::expect_used)] // reason: test -- panics indicate broken test infrastructure
#[allow(clippy::disallowed_methods)] // reason: test uses Command and fs
fn ts_init_force_removes_old_subsections() {
    let tmp = tempfile::tempdir().expect("failed to create temp dir");
    let dir = tmp.path();

    // Write guardrail3.toml with existing [typescript] and [rust] sections
    std::fs::write(
        dir.join("guardrail3.toml"),
        concat!(
            "version = \"0.1\"\n",
            "\n",
            "[profile]\n",
            "name = \"service\"\n",
            "\n",
            "[typescript]\n",
            "\n",
            "[typescript.apps.old-app]\n",
            "type = \"service\"\n",
            "\n",
            "[typescript.apps.old-app.checks]\n",
            "architecture = true\n",
            "content = false\n",
            "tests = true\n",
            "\n",
            "[rust]\n",
            "workspace_root = \".\"\n",
        ),
    )
    .expect("write guardrail3.toml with old typescript");

    // Create apps/new-app/package.json so ts init discovers it
    let new_app_dir = dir.join("apps/new-app");
    std::fs::create_dir_all(&new_app_dir).expect("create apps/new-app");
    std::fs::write(
        new_app_dir.join("package.json"),
        r#"{"name": "new-app", "version": "1.0.0"}"#,
    )
    .expect("write package.json");

    let path_str = dir.to_str().expect("non-utf8 path");
    let out = guardrail3()
        .args(["ts", "init", "--force", path_str])
        .output()
        .expect("failed to run ts init");

    assert!(
        out.status.success(),
        "ts init --force should succeed: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    // Read resulting guardrail3.toml
    let config =
        std::fs::read_to_string(dir.join("guardrail3.toml")).expect("read updated guardrail3.toml");

    // [rust] section should be preserved
    assert!(
        config.contains("[rust]"),
        "[rust] section should be preserved, got:\n{config}"
    );
    assert!(
        config.contains("workspace_root"),
        "workspace_root should be preserved, got:\n{config}"
    );

    // old-app should NOT appear
    assert!(
        !config.contains("old-app"),
        "old-app should be removed by --force, got:\n{config}"
    );

    // new-app should appear in the new typescript section
    assert!(
        config.contains("new-app"),
        "new-app should be discovered and added, got:\n{config}"
    );
}
