profile = "library"

allowed_deps = [
  "deny-toml-parser",
  "g3rs-deny-config-checks",
  "g3rs-deny-config-checks-assertions",
  "g3rs-deny-filetree-checks",
  "g3rs-deny-filetree-checks-assertions",
  "g3rs-deny-ingestion-assertions",
  "g3rs-deny-ingestion-runtime",
  "g3rs-deny-ingestion-types",
  "g3rs-deny-types",
  "g3-workspace-crawl",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "tempfile",
]

[checks]
garde = false
