profile = "service"

allowed_deps = [
  "clap",
  "g3-workspace-crawl",
  "g3ts-eslint-config-checks",
  "g3ts-eslint-ingestion",
  "g3ts-arch-config-checks",
  "g3ts-arch-file-tree-checks",
  "g3ts-arch-ingestion",
  "g3ts-arch-source-checks",
  "g3ts-tsconfig-config-checks",
  "g3ts-tsconfig-ingestion",
  "g3ts-package-config-checks",
  "g3ts-package-ingestion",
  "g3ts-npmrc-config-checks",
  "g3ts-npmrc-ingestion",
  "g3ts-jscpd-config-checks",
  "g3ts-jscpd-ingestion",
  "g3ts",
  "guardrail3-check-types",
  "guardrail3-ts-app-types",
  "guardrail3-ts-assertions",
  "guardrail3-ts-family-runner-config",
  "guardrail3-ts-family-runner-structure",
  "guardrail3-ts-packages",
  "guardrail3-ts-report",
  "guardrail3-ts-report-assertions",
  "guardrail3-ts-validate-command",
  "guardrail3-ts-validate-command-assertions",
  "tempfile",
]
