#[cfg(feature = "api")]
mod types;

#[cfg(feature = "api")]
pub type G3TsAstroAppRootInput = types::G3TsAstroAppRootInput;
#[cfg(feature = "api")]
pub type G3TsAstroContentAdapterSourcePaths = types::G3TsAstroContentAdapterSourcePaths;
#[cfg(feature = "api")]
pub type G3TsAstroMdxApprovedSourcePaths = types::G3TsAstroMdxApprovedSourcePaths;
#[cfg(feature = "api")]
pub type G3TsAstroPolicyModuleSourcePaths = types::G3TsAstroPolicyModuleSourcePaths;
#[cfg(feature = "api")]
pub type G3TsAstroSeoApprovedSourcePaths = types::G3TsAstroSeoApprovedSourcePaths;
#[cfg(feature = "api")]
pub type G3TsAstroCallSnapshot = types::G3TsAstroCallSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroConfigSurfaceSnapshot = types::G3TsAstroConfigSurfaceSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroConfigSurfaceState = types::G3TsAstroConfigSurfaceState;
#[cfg(feature = "api")]
pub type G3TsAstroContentMode = types::G3TsAstroContentMode;
#[cfg(feature = "api")]
pub type G3TsAstroEslintPluginContractInput = types::G3TsAstroEslintPluginContractInput;
#[cfg(feature = "api")]
pub type G3TsAstroEslintSurfaceSnapshot = types::G3TsAstroEslintSurfaceSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroEslintSurfaceState = types::G3TsAstroEslintSurfaceState;
#[cfg(feature = "api")]
pub type G3TsAstroIntegrationSnapshot = types::G3TsAstroIntegrationSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroOutputMode = types::G3TsAstroOutputMode;
#[cfg(feature = "api")]
pub type G3TsAstroPackageScriptCommand = types::G3TsAstroPackageScriptCommand;
#[cfg(feature = "api")]
pub type G3TsAstroPackageScriptCommandSeparator = types::G3TsAstroPackageScriptCommandSeparator;
#[cfg(feature = "api")]
pub type G3TsAstroPackageScriptParseBlocker = types::G3TsAstroPackageScriptParseBlocker;
#[cfg(feature = "api")]
pub type G3TsAstroPackageScriptToolInvocation = types::G3TsAstroPackageScriptToolInvocation;
#[cfg(feature = "api")]
pub type G3TsAstroPackageSurfaceSnapshot = types::G3TsAstroPackageSurfaceSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroPackageSurfaceState = types::G3TsAstroPackageSurfaceState;
#[cfg(feature = "api")]
pub type G3TsAstroPipelineRuleScopeSnapshot = types::G3TsAstroPipelineRuleScopeSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroPolicySnapshot = types::G3TsAstroPolicySnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroPolicySurfaceState = types::G3TsAstroPolicySurfaceState;
#[cfg(feature = "api")]
pub type G3TsAstroRouteMarkdownPageInput = types::G3TsAstroRouteMarkdownPageInput;
#[cfg(feature = "api")]
pub type G3TsAstroStaticObjectProperty = types::G3TsAstroStaticObjectProperty;
#[cfg(feature = "api")]
pub type G3TsAstroStaticValue = types::G3TsAstroStaticValue;
#[cfg(feature = "api")]
pub type G3TsAstroSyncpackConfigSnapshot = types::G3TsAstroSyncpackConfigSnapshot;
#[cfg(feature = "api")]
pub type G3TsAstroSyncpackConfigState = types::G3TsAstroSyncpackConfigState;
#[cfg(feature = "api")]
pub type G3TsAstroSyncpackRequiredPin = types::G3TsAstroSyncpackRequiredPin;
#[cfg(feature = "api")]
pub type G3TsAstroContentConfigChecksInput = types::G3TsAstroContentConfigChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroContentIntegrationContractInput = types::G3TsAstroContentIntegrationContractInput;
#[cfg(feature = "api")]
pub type G3TsAstroContentFileTreeChecksInput = types::G3TsAstroContentFileTreeChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroMdxConfigChecksInput = types::G3TsAstroMdxConfigChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroMdxIntegrationContractInput = types::G3TsAstroMdxIntegrationContractInput;
#[cfg(feature = "api")]
pub type G3TsAstroSeoConfigChecksInput = types::G3TsAstroSeoConfigChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroSeoIntegrationContractInput = types::G3TsAstroSeoIntegrationContractInput;
#[cfg(feature = "api")]
pub type G3TsAstroSetupConfigChecksInput = types::G3TsAstroSetupConfigChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroSetupIntegrationContractInput = types::G3TsAstroSetupIntegrationContractInput;
#[cfg(feature = "api")]
pub type G3TsAstroSetupFileTreeChecksInput = types::G3TsAstroSetupFileTreeChecksInput;
#[cfg(feature = "api")]
pub type G3TsAstroStateFileTreeChecksInput = types::G3TsAstroStateFileTreeChecksInput;
