profile = "library"

allowed_deps = [
  "g3-workspace-crawl",
  "g3ts-astro-check-support",
  "g3ts-astro-state-types",
  "globset",
  "g3ts-toml-parser",
  "package-json-parser",
]

[checks]
garde = false
