mod run;
mod support;
mod ts_astro_config_01_astro_package_present;
mod ts_astro_config_02_astro_check_present;
mod ts_astro_config_03_astro_eslint_plugin_package_present;
mod ts_astro_config_05_astro_eslint_plugin_wired;
mod ts_astro_config_06_pipeline_plugin_package_present;
mod ts_astro_config_07_pipeline_plugin_wired;
mod ts_astro_config_08_syncpack_package_and_script;
mod ts_astro_config_09_syncpack_stack_pins;
mod ts_astro_config_10_syncpack_forbidden_deps;

#[cfg(feature = "checks")]
pub use run::check;
