profile = "library"

allowed_deps = [
  "g3-workspace-crawl",
  "g3rs-workspace-crawl",
  "g3ts-astro-content-config-checks",
  "g3ts-astro-content-file-tree-checks",
  "g3ts-astro-ingestion",
  "g3ts-astro-mdx-config-checks",
  "g3ts-astro-seo-config-checks",
  "g3ts-astro-setup-config-checks",
  "g3ts-astro-setup-file-tree-checks",
  "g3ts-astro-state-file-tree-checks",
  "guardrail3-check-types",
]

[checks]
garde = false
