use guardrail3_app_rs_family_test as _;

#[cfg(feature = "checks")]
pub mod rs_test_01_inline_test_bodies;
#[cfg(feature = "checks")]
pub mod rs_test_02_owned_sidecar_shape;
#[cfg(feature = "checks")]
pub mod rs_test_03_runtime_assertions_split;
#[cfg(feature = "checks")]
pub mod rs_test_04_ignore_reason;
#[cfg(feature = "checks")]
pub mod rs_test_05_should_panic_expected;
#[cfg(feature = "checks")]
pub mod rs_test_06_tautological_assertions;
#[cfg(feature = "checks")]
pub mod rs_test_07_real_proof_site;
#[cfg(feature = "checks")]
pub mod rs_test_08_weak_matches_assert;
#[cfg(feature = "checks")]
pub mod rs_test_09_nextest_timeouts;
#[cfg(feature = "checks")]
pub mod rs_test_10_input_failures;
#[cfg(feature = "checks")]
pub mod rs_test_11_cargo_mutants_installed;
#[cfg(feature = "checks")]
pub mod rs_test_12_mutants_toml_exists;
#[cfg(feature = "checks")]
pub mod rs_test_13_mutants_profile_present;
#[cfg(feature = "checks")]
pub mod rs_test_14_mutation_hook_present;
#[cfg(feature = "checks")]
pub mod rs_test_15_mutants_config_sane;
#[cfg(feature = "checks")]
pub mod rs_test_16_assertions_modules_prove;
#[cfg(feature = "checks")]
pub mod rs_test_17_external_harnesses_use_assertions;
#[cfg(feature = "checks")]
pub mod rs_test_18_test_support_generic;
