use guardrail3_app_rs_family_clippy as _;
use guardrail3_domain_report as _;

#[cfg(feature = "checks")]
pub mod facts;
#[cfg(feature = "checks")]
pub mod rs_clippy_01_coverage;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_01_max_struct_bools;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_02_max_fn_params_bools;
#[cfg(feature = "checks")]
pub mod rs_clippy_04_missing_method_ban;
#[cfg(feature = "checks")]
pub mod rs_clippy_05_missing_type_ban;
#[cfg(feature = "checks")]
pub mod rs_clippy_06_extra_method_ban;
#[cfg(feature = "checks")]
pub mod rs_clippy_07_extra_type_ban;
#[cfg(feature = "checks")]
pub mod rs_clippy_08_reason_quality;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_03_too_many_lines_threshold;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_04_too_many_arguments_threshold;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_05_excessive_nesting_threshold;
#[cfg(feature = "checks")]
pub mod rs_clippy_12_allowed_placement;
#[cfg(feature = "checks")]
pub mod rs_clippy_13_local_policy_root_baseline;
#[cfg(feature = "checks")]
pub mod rs_clippy_14_library_global_state;
#[cfg(feature = "checks")]
pub mod rs_clippy_15_trivial_reason;
#[cfg(feature = "checks")]
pub mod rs_clippy_16_avoid_breaking_exported_api;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_06_test_relaxations;
#[cfg(feature = "checks")]
pub mod rs_clippy_18_duplicate_bans;
#[cfg(feature = "checks")]
pub mod rs_clippy_19_unknown_keys;
#[cfg(feature = "checks")]
pub mod rs_clippy_20_macro_bans;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_07_cognitive_complexity_threshold;
#[cfg(feature = "checks")]
pub mod rs_clippy_config_08_type_complexity_threshold;
#[cfg(feature = "checks")]
pub mod rs_clippy_23_policy_context_parseable;
#[cfg(feature = "checks")]
pub mod rs_clippy_24_forbid_clippy_conf_dir_override;
#[cfg(feature = "checks")]
pub mod rs_clippy_25_config_parseable;
