profile = "library"

allowed_deps = [
  "g3rs-workspace-crawl",
  "g3-workspace-crawl",
  "g3ts-fmt-ingestion-runtime",
  "g3ts-fmt-ingestion-assertions",
  "g3ts-fmt-types",
  "package-json-parser",
  "package-script-command-parser",
  "syncpack-config-parser",
]

[checks]
garde = false
