profile = "library"

allowed_deps = [
  "g3rs-workspace-crawl",
  "g3rs-workspace-crawl-assertions",
  "g3rs-workspace-crawl-runtime",
  "g3rs-workspace-crawl-types",
  "ignore",
  "tempfile",
  "walkdir",
]

[checks]
garde = false
