pub const TOP_LEVEL_HELP: &str = "\
===============================================================================
COMMAND REFERENCE
===============================================================================

RUST:
  guardrail3 rs init [PATH] [OPTIONS]
    --profile <service|library>        Default: service
    --force                            Overwrite existing files

  guardrail3 rs generate [PATH]
    Produces: clippy.toml, deny.toml, rustfmt.toml, rust-toolchain.toml,
    release-plz.toml, cliff.toml, .githooks/pre-commit

  guardrail3 rs validate [PATH] [OPTIONS]
    --format <text|json|md>            Default: text
    --staged                           Only git-staged files
    --dirty                            Staged + unstaged files
    --commits <N>                      Files changed in last N commits
    --files <FILE...>                  Specific files only
    --family <NAME>                    Repeat to select Rust families
    --thorough                         Include slow release checks
    --inventory                        Show passing/inventory checks
    --verbose                          Show every summarized item

  guardrail3 rs check [PATH]           CI: verify generated configs are current
  guardrail3 rs diff [PATH]            Dry-run of rs generate (show diffs)
  guardrail3 rs hooks-install [PATH]   Regenerate pre-commit hook only
  guardrail3 rs list-modules           List embedded config modules
  guardrail3 rs show-module <NAME>     Print module content

TYPESCRIPT:
  guardrail3 ts init [PATH] [OPTIONS]
  guardrail3 ts generate [PATH]
  guardrail3 ts validate [PATH] [OPTIONS]
    --format <text|json|md>
    --staged | --dirty | --commits <N> | --files <FILE...>
    --inventory
    --verbose
  guardrail3 ts hooks-install [PATH]
  guardrail3 ts hooks-validate [PATH]

===============================================================================
SETUP GUIDE
===============================================================================

1. Run `guardrail3 rs init` or `guardrail3 ts init`.
2. Review `guardrail3.toml`.
3. Run `guardrail3 rs generate` / `guardrail3 ts generate`.
4. Run `guardrail3 rs validate` / `guardrail3 ts validate`.
5. Use `guardrail3 rs check` in CI to detect stale generated Rust configs.
";

pub const RS_HELP: &str = "\
  init           Create guardrail3.toml
  generate       Produce Rust guardrail config files and hooks
  validate       Run Rust family checks
  check          CI: verify generated configs are current
  diff           Dry-run generate (show what would change)
  hooks-install  Regenerate pre-commit hook
  list-modules   List embedded config modules
  show-module    Print module content";

pub const TS_HELP: &str = "\
  init           Create [typescript] section in guardrail3.toml
  generate       Produce TypeScript config files and hooks
  validate       Run TypeScript checks
  hooks-install  Regenerate pre-commit hook
  hooks-validate Check hook configuration";

pub const RS_VALIDATE_HELP: &str = "\
RUST VALIDATION FAMILIES

  arch
  fmt
  toolchain
  clippy
  deny
  cargo
  code
  hexarch
  libarch
  deps
  garde
  test
  release
  hooks-shared
  hooks-rs        (implies hooks-shared)

EXAMPLES

  guardrail3 rs validate .
  guardrail3 rs validate . --family arch
  guardrail3 rs validate . --family hexarch
  guardrail3 rs validate . --family code --family garde --staged
  guardrail3 rs validate . --family release --thorough
  guardrail3 rs validate . --family hooks-rs

CONFIG

  [rust.checks]
  arch = true
  fmt = true
  toolchain = true
  clippy = true
  deny = true
  cargo = true
  code = true
  hexarch = true
  libarch = true
  deps = true
  garde = true
  test = true
  release = true
  hooks_shared = true
  hooks_rs = true

OUTPUT

  Rust validate emits only `RS-*` and `HOOK-*` findings.
  Sections are one-to-one with selected Rust families.
";

pub const TS_VALIDATE_HELP: &str = "\
TYPESCRIPT VALIDATION

TypeScript validate keeps the shared scope flags:
  --staged
  --dirty
  --commits <N>
  --files <FILE...>

JSON output uses the same report schema as Rust validate.
";

pub const RS_INIT_HELP: &str = "\
PROFILES

  service    For HTTP services, CLI tools, and binaries.
  library    For pure logic packages.

RUST CHECK TOGGLES

  `rs init` writes family-based Rust check toggles:
    arch, fmt, toolchain, clippy, deny, cargo, code, hexarch, deps,
    libarch, garde, test, release, hooks_shared, hooks_rs

AFTER INIT

  guardrail3 rs generate
  guardrail3 rs validate .
";

pub const TS_INIT_HELP: &str = "\
TypeScript init creates or updates the `[typescript]` section in `guardrail3.toml`.
Run `guardrail3 ts generate` after editing config.
";

pub const GUIDE_CONTENT: &str = r#"# GUARDRAIL3 GUIDE

> This file was generated by `guardrail3 guide`. Do not edit manually.
> Regenerate after updating guardrail3: `guardrail3 guide`

## Command Reference

### Rust

```text
guardrail3 rs init [PATH] --profile <service|library> [--force]
guardrail3 rs generate [PATH]
guardrail3 rs validate [PATH] [--family <NAME> ...] [--staged|--dirty|--commits N|--files ...]
guardrail3 rs check [PATH]
guardrail3 rs hooks-install [PATH]
guardrail3 rs list-modules
guardrail3 rs show-module <NAME>
```

Rust validate families:

```text
arch
fmt
toolchain
clippy
deny
cargo
code
hexarch
libarch
deps
garde
test
release
hooks-shared
hooks-rs
```

`hooks-rs` implies `hooks-shared`.

Examples:

```text
guardrail3 rs validate .
guardrail3 rs validate . --family arch
guardrail3 rs validate . --family hexarch
guardrail3 rs validate . --family code --family garde --staged
guardrail3 rs validate . --family release --thorough
```

### TypeScript

```text
guardrail3 ts init [PATH] [--force]
guardrail3 ts generate [PATH]
guardrail3 ts validate [PATH] [--staged|--dirty|--commits N|--files ...]
guardrail3 ts hooks-install [PATH]
guardrail3 ts hooks-validate [PATH]
```

## Config File

Only `generate` / `check` depend on `guardrail3.toml`. Rust validate also reads it for family enable/disable policy and fails closed if `[rust.checks]` is malformed.

### Rust family toggles

```toml
[rust.checks]
arch = true
fmt = true
toolchain = true
clippy = true
deny = true
cargo = true
code = true
hexarch = true
libarch = true
deps = true
garde = true
test = true
release = true
hooks_shared = true
hooks_rs = true
```

Per-app and package overrides use the scoped family names only. `arch` stays global-only under `[rust.checks]`:

```toml
[rust.apps.my_api.checks]
hexarch = true
garde = false

[rust.packages.checks]
libarch = true
code = true
test = true
release = false
```

Removed Rust check keys:

```toml
architecture
tests
hooks
```

Use:

```toml
hexarch
test
hooks_shared
hooks_rs
```

## Profiles

`service`
- For binaries and services that do I/O.
- Services typically live under `apps/` and use hex arch.

`library`
- For shared packages with no uncontrolled I/O.
- Libraries typically live under `packages/` and use `allowed_deps`.

## Architecture Convention

Rust services:

```text
apps/my-api/
  crates/
    domain/
    ports/
      inbound/
      outbound/
    app/
    adapters/
      inbound/api/
      outbound/
```

Rust libraries:

```text
packages/my-lib/
```

TypeScript services:

```text
apps/my-app/src/
  modules/
    domain/
    ports/
      inbound/
      outbound/
    application/
    adapters/
      inbound/api/
      outbound/
```

## Generated Files

Rust generation can write:

```text
clippy.toml
deny.toml
rustfmt.toml
rust-toolchain.toml
release-plz.toml
cliff.toml
.githooks/pre-commit
```

TypeScript generation can write:

```text
eslint.config.mjs
tsconfig.base.json
.npmrc
.jscpd.json
.githooks/pre-commit
```

## Output

`guardrail3 rs validate` emits only `RS-*` and `HOOK-*` findings.

JSON output shape:

```json
{
  "project": "<path>",
  "stacks": ["Rust"],
  "sections": [
    {
      "name": "hexarch",
      "results": [
        {
          "id": "RS-HEXARCH-01",
          "severity": "error|warn|info",
          "title": "<short title>",
          "message": "<detailed message>",
          "file": "<absolute path or null>",
          "file_relative": "<relative path or null>",
          "line": "<line number or null>",
          "inventory": true|false
        }
      ]
    }
  ],
  "summary": {
    "errors": 0,
    "warnings": 0,
    "info": 0
  }
}
```
"#;
