pub mod rs_release_01_license_file;
pub mod rs_release_02_release_plz_exists;
pub mod rs_release_03_release_plz_coverage;
pub mod rs_release_04_cliff_exists;
pub mod rs_release_05_release_plz_workflow;
pub mod rs_release_06_publish_dry_run_workflow;
pub mod rs_release_07_registry_token;
pub mod rs_release_08_semver_checks_installed;
