profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "g3rs-toolchain-config-checks",
  "g3rs-toolchain-filetree-checks",
  "g3rs-toolchain-ingestion-runtime",
  "g3rs-toolchain-ingestion-types",
  "g3rs-toolchain-types",
  "g3-workspace-crawl",
  "guardrail3-check-types",
  "rust-toolchain-toml-parser",
]

[checks]
garde = false
