profile = "library"

allowed_deps = [
  "g3-workspace-crawl",
  "g3ts-package-types",
  "package-json-parser",
  "package-script-command-parser",
  "serde",
  "serde_norway",
  "syncpack-config-parser",
  "tempfile",
]

[checks]
garde = false
