profile = "library"

allowed_deps = [
  "g3rs-apparch-config-checks-assertions",
  "g3rs-apparch-config-checks-runtime",
  "g3rs-apparch-types",
  "guardrail3-check-types",
  "guardrail3-reason-policy",
  "guardrail3-rs-toml-parser",
]

[checks]
garde = false
