use guardrail3_app_rs_family_libarch as _;

mod common;

pub mod rs_libarch_04_exact_layered_crate_set;
pub mod rs_libarch_07_core_no_api_dep;
pub mod rs_libarch_08_core_no_infra_dep;
pub mod rs_libarch_09_api_no_infra_dep;
pub mod rs_libarch_10_infra_not_public_surface;
pub mod rs_libarch_11_root_facade_exports_api;

pub use rs_libarch_07_core_no_api_dep as rs_libarch_07_core_must_not_depend_on_api;
pub use rs_libarch_08_core_no_infra_dep as rs_libarch_08_core_must_not_depend_on_infra;
pub use rs_libarch_09_api_no_infra_dep as rs_libarch_09_api_must_not_depend_on_infra;
pub use rs_libarch_11_root_facade_exports_api as rs_libarch_11_root_facade_exports_from_api;
