use guardrail3_app_rs_family_code as _;

mod finding_support;

pub mod comments;
pub mod parse;
#[path = "lint_policy/rs_code_01_crate_level_allow.rs"]
pub mod rs_code_01_crate_level_allow;
#[path = "lint_policy/rs_code_02_unused_crate_dependencies_allow.rs"]
pub mod rs_code_02_unused_crate_dependencies_allow;
#[path = "lint_policy/rs_code_03_item_level_allow_without_reason.rs"]
pub mod rs_code_03_item_level_allow_without_reason;
#[path = "lint_policy/rs_code_04_item_level_allow_with_reason.rs"]
pub mod rs_code_04_item_level_allow_with_reason;
#[path = "hygiene/rs_code_05_garde_skip_without_comment.rs"]
pub mod rs_code_05_garde_skip_without_comment;
#[path = "hygiene/rs_code_06_garde_skip_with_comment.rs"]
pub mod rs_code_06_garde_skip_with_comment;
#[path = "lint_policy/rs_code_07_exception_comment_inventory.rs"]
pub mod rs_code_07_exception_comment_inventory;
#[path = "lint_policy/rs_code_08_cfg_attr_allow_inventory.rs"]
pub mod rs_code_08_cfg_attr_allow_inventory;
#[path = "hygiene/rs_code_09_file_length.rs"]
pub mod rs_code_09_file_length;
#[path = "hygiene/rs_code_10_use_count_error.rs"]
pub mod rs_code_10_use_count_error;
#[path = "hygiene/rs_code_11_use_count_warn.rs"]
pub mod rs_code_11_use_count_warn;
#[path = "lint_policy/rs_code_12_unsafe_code_lint.rs"]
pub mod rs_code_12_unsafe_code_lint;
#[path = "hygiene/rs_code_13_todo_macros.rs"]
pub mod rs_code_13_todo_macros;
#[path = "hygiene/rs_code_15_direct_fs_usage.rs"]
pub mod rs_code_15_direct_fs_usage;
#[path = "hygiene/rs_code_16_panic_macro.rs"]
pub mod rs_code_16_panic_macro;
#[path = "cfg_and_paths/rs_code_17_impl_allow_blast_radius.rs"]
pub mod rs_code_17_impl_allow_blast_radius;
#[path = "cfg_and_paths/rs_code_18_always_true_cfg_attr_bypass.rs"]
pub mod rs_code_18_always_true_cfg_attr_bypass;
#[path = "inventory/rs_code_19_large_type_inventory.rs"]
pub mod rs_code_19_large_type_inventory;
#[path = "cfg_and_paths/rs_code_20_extern_allow.rs"]
pub mod rs_code_20_extern_allow;
#[path = "cfg_and_paths/rs_code_21_fs_glob_import.rs"]
pub mod rs_code_21_fs_glob_import;
#[path = "lint_policy/rs_code_22_deny_forbid_without_reason.rs"]
pub mod rs_code_22_deny_forbid_without_reason;
#[path = "cfg_and_paths/rs_code_23_include_bypass.rs"]
pub mod rs_code_23_include_bypass;
// RS-CODE-24 removed: #[path] detection moved to RS-ARCH-09.
#[path = "api_shape/rs_code_25_public_result_error_type.rs"]
pub mod rs_code_25_public_result_error_type;
#[path = "api_shape/rs_code_26_lib_glob_reexport.rs"]
pub mod rs_code_26_lib_glob_reexport;
#[path = "api_shape/rs_code_27_facade_only_lib.rs"]
pub mod rs_code_27_facade_only_lib;
#[path = "inventory/rs_code_29_large_trait_inventory.rs"]
pub mod rs_code_29_large_trait_inventory;
#[path = "lint_policy/rs_code_30_input_failures.rs"]
pub mod rs_code_30_input_failures;
#[path = "api_shape/rs_code_31_public_struct_named_fields.rs"]
pub mod rs_code_31_public_struct_named_fields;
#[path = "inventory/rs_code_32_test_expect_message_quality.rs"]
pub mod rs_code_32_test_expect_message_quality;
#[path = "api_shape/rs_code_33_public_weak_error_forms.rs"]
pub mod rs_code_33_public_weak_error_forms;
#[path = "api_shape/rs_code_34_generic_parameter_cap.rs"]
pub mod rs_code_34_generic_parameter_cap;
#[path = "inventory/rs_code_35_root_structural_cap.rs"]
pub mod rs_code_35_root_structural_cap;
#[path = "cfg_and_paths/rs_code_36_string_dispatch_cap.rs"]
pub mod rs_code_36_string_dispatch_cap;
