profile = "library"

allowed_deps = [
  "eslint-config-parser",
  "eslint-directive-parser",
  "g3-workspace-crawl",
  "g3ts-style-ingestion-runtime",
  "g3ts-style-ingestion-assertions",
  "g3ts-style-types",
  "g3ts-toml-parser",
  "globset",
  "package-json-parser",
  "package-script-command-parser",
  "serde_json",
  "stylelint-config-parser",
  "syncpack-config-parser",
]

[checks]
garde = false
