profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "g3rs-apparch-config-checks",
  "g3rs-apparch-ingestion-assertions",
  "g3rs-apparch-ingestion-runtime",
  "g3rs-apparch-source-checks",
  "g3rs-apparch-types",
  "g3-workspace-crawl",
  "glob",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "syn",
  "tempfile",
]

[checks]
garde = false
