mod common;
#[cfg(feature = "checks")]
use g3rs_clippy_config_checks_runtime as _;

#[cfg(feature = "checks")]
pub mod avoid_breaking_exported_api;
#[cfg(feature = "checks")]
pub mod ban_reason_quality;
#[cfg(feature = "checks")]
pub mod cognitive_complexity_threshold;
#[cfg(feature = "checks")]
pub mod config_parseable;
#[cfg(feature = "checks")]
pub mod duplicate_bans;
#[cfg(feature = "checks")]
pub mod excessive_nesting_threshold;
#[cfg(feature = "checks")]
pub mod extra_method_ban;
#[cfg(feature = "checks")]
pub mod extra_type_ban;
#[cfg(feature = "checks")]
pub mod forbid_clippy_conf_dir_override;
#[cfg(feature = "checks")]
pub mod library_global_state;
#[cfg(feature = "checks")]
pub mod macro_bans;
#[cfg(feature = "checks")]
pub mod max_fn_params_bools;
#[cfg(feature = "checks")]
pub mod max_struct_bools;
#[cfg(feature = "checks")]
pub mod missing_method_ban;
#[cfg(feature = "checks")]
pub mod missing_type_ban;
#[cfg(feature = "checks")]
pub mod policy_context_parseable;
#[cfg(feature = "checks")]
pub mod test_relaxations;
#[cfg(feature = "checks")]
pub mod too_many_arguments_threshold;
#[cfg(feature = "checks")]
pub mod too_many_lines_threshold;
#[cfg(feature = "checks")]
pub mod type_complexity_threshold;
#[cfg(feature = "checks")]
pub mod unknown_keys;
