profile = "library"

allowed_deps = [
  "g3ts-typecov-config-checks-runtime",
  "g3ts-typecov-config-checks-assertions",
  "g3ts-typecov-types",
  "guardrail3-check-types",
  "syncpack-config-parser",
]

[checks]
garde = false
