mod baseline;
pub(crate) mod support;
pub(crate) mod ts_eslint_config_07_thresholds;
pub(crate) mod ts_eslint_config_08_core_baseline_rules;
pub(crate) mod ts_eslint_config_09_type_safety_rules;
pub(crate) mod ts_eslint_config_10_hygiene_rules;
pub(crate) mod ts_eslint_config_11_unicorn_rules;
pub(crate) mod ts_eslint_config_12_regexp_rules;
pub(crate) mod ts_eslint_config_13_sonarjs_rules;
pub(crate) mod ts_eslint_config_14_test_relaxations;
pub(crate) mod ts_eslint_config_15_js_carveout;
