pub mod hook_shared_10_shell_error_handling;
pub mod hook_shared_11_valid_shebang;
pub mod hook_shared_13_no_unconditional_exit_zero;
pub mod hook_shared_14_no_bypass_instructions;
pub mod hook_shared_18_executable_command_context_only;
pub mod hook_shared_19_real_dispatcher_syntax_only;
pub mod hook_shared_20_concrete_lockfile_command;
pub mod hook_shared_21_no_fail_open_wrappers;
