use guardrail3_app_rs_family_hexarch as _;

#[cfg(feature = "checks")]
pub mod dependency_facts;
#[cfg(feature = "checks")]
pub mod inventory_contract;
#[cfg(feature = "checks")]
pub use inventory_contract::{
    HEXARCH_INVENTORY_RULE_IDS, PATCH_REPLACE_BYPASS_RULE_ID, assert_inventory_ids,
    assert_inventory_result,
};
#[path = "structure/rs_hexarch_01_crates_exists.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_01_crates_exists;
#[path = "structure/rs_hexarch_02_exact_contents.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_02_exact_contents;
#[path = "structure/rs_hexarch_03_inbound_outbound.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_03_inbound_outbound;
#[path = "structure/rs_hexarch_04_loose_files.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_04_loose_files;
#[path = "structure/rs_hexarch_05_container_not_empty.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_05_container_not_empty;
#[path = "structure/rs_hexarch_06_leaf_valid.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_06_leaf_valid;
#[path = "workspace_policy/rs_hexarch_08_app_cargo_is_workspace.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_08_app_cargo_is_workspace;
#[path = "workspace_policy/rs_hexarch_10_members_within_app_boundary.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_10_members_within_app_boundary;
#[path = "workspace_policy/rs_hexarch_11_root_workspace_doesnt_include_apps.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_11_root_workspace_doesnt_include_apps;
#[path = "workspace_policy/rs_hexarch_12_src_banned.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_12_src_banned;
#[path = "dependency_policy/rs_hexarch_13_dependency_direction.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_13_dependency_direction;
#[path = "dependency_policy/rs_hexarch_14_dependency_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_14_dependency_inventory;
#[path = "dependency_policy/rs_hexarch_15_boundary_config.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_15_boundary_config;
#[path = "dependency_policy/rs_hexarch_16_patch_replace_bypass.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_16_patch_replace_bypass;
#[path = "dependency_policy/rs_hexarch_17_workspace_inherited_direction.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_17_workspace_inherited_direction;
#[path = "dependency_policy/rs_hexarch_18_renamed_dependency_direction.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_18_renamed_dependency_direction;
#[path = "dependency_integrity/rs_hexarch_19_same_layer_cycles.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_19_same_layer_cycles;
#[path = "dependency_integrity/rs_hexarch_20_dev_dependency_direction.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_20_dev_dependency_direction;
#[path = "dependency_integrity/rs_hexarch_21_domain_purity.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_21_domain_purity;
#[path = "dependency_integrity/rs_hexarch_22_ports_trait_dominance.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_22_ports_trait_dominance;
#[path = "dependency_integrity/rs_hexarch_23_adapter_pub_trait.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_23_adapter_pub_trait;
#[path = "dependency_integrity/rs_hexarch_24_cross_app_boundary.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_24_cross_app_boundary;
#[path = "dependency_integrity/rs_hexarch_25_target_dependency_direction.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_25_target_dependency_direction;
#[path = "dependency_integrity/rs_hexarch_26_member_manifest_parse_error.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_26_member_manifest_parse_error;
#[path = "dependency_integrity/rs_hexarch_27_nested_workspace_forbidden.rs"]
#[cfg(feature = "checks")]
pub mod rs_hexarch_27_nested_workspace_forbidden;
