profile = "library"

allowed_deps = [
  "g3-guardrail-toml-types",
  "cargo-config-toml-parser",
  "cargo-toml-parser",
  "clippy-toml-parser",
  "g3rs-clippy-types",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "toml",
]

[checks]
garde = false
