use super::*;

#[test]
fn base_config_header_imports_and_structure() {
    let result = build_eslint_config(false, false);
    assert!(result.starts_with("// GENERATED by guardrail3"));
    assert!(result.contains("@ts-check"));
    for imp in &[
        "js",
        "tseslint",
        "unicorn",
        "regexp",
        "sonarjs",
        "react",
        "reactHooks",
    ] {
        assert!(
            result.contains(&format!("import {imp} from")),
            "missing import: {imp}"
        );
    }
    assert!(!result.contains("jsx-a11y"));
    assert!(!result.contains("tailwind-ban"));
    assert!(!result.contains("eslint-plugin-boundaries"));
    assert!(result.contains("export default tseslint.config("));
    assert!(result.contains("js.configs.recommended"));
    assert!(result.contains("...tseslint.configs.strictTypeChecked"));
    assert!(result.contains("projectService: true"));
    assert!(result.ends_with(");\n"));
}

#[test]
fn conditional_content_app_sections() {
    let result = build_eslint_config(true, false);
    assert!(result.contains(r#"import jsxA11y from "eslint-plugin-jsx-a11y""#));
    assert!(result.contains(r#"import tailwindBan from "eslint-plugin-tailwind-ban""#));
    assert!(result.contains("jsxA11y.flatConfigs.strict"));
    assert!(result.contains("tailwind-ban/ban-classes"));
    assert!(!result.contains("eslint-plugin-boundaries"));
}

#[test]
fn conditional_service_app_sections() {
    let result = build_eslint_config(false, true);
    assert!(result.contains(r#"import boundaries from "eslint-plugin-boundaries""#));
    assert!(result.contains("boundaries/element-types"));
    assert!(!result.contains("jsx-a11y"));
}

#[test]
fn both_flags_include_all_sections() {
    let result = build_eslint_config(true, true);
    assert!(result.contains("jsxA11y"));
    assert!(result.contains("tailwindBan"));
    assert!(result.contains("boundaries"));
}

#[test]
fn config_has_global_ignores() {
    let result = build_eslint_config(false, false);
    for pattern in &[
        "node_modules/**",
        ".next/**",
        "dist/**",
        "target/**",
        "drizzle/**",
        "*.generated.*",
        ".plans/**",
        ".worklogs/**",
        "coverage/**",
        ".claude/**",
    ] {
        assert!(result.contains(pattern), "missing ignore: {pattern}");
    }
}

#[test]
fn config_has_plugin_rules() {
    let result = build_eslint_config(false, false);
    assert!(result.contains(r#""unicorn/no-null": "off""#));
    assert!(result.contains(r#""unicorn/no-anonymous-default-export": "error""#));
    assert!(result.contains(r#""regexp/require-unicode-regexp": "error""#));
    assert!(result.contains(r#""regexp/no-misleading-capturing-group": "error""#));
    assert!(result.contains(r#""sonarjs/cognitive-complexity": "error""#));
    assert!(result.contains(r#""sonarjs/no-useless-react-setstate": "error""#));
    assert!(result.contains(r#""react/no-unstable-nested-components": "error""#));
    assert!(result.contains("validStrategies"));
}

#[test]
fn config_has_core_and_ts_rules() {
    let result = build_eslint_config(false, false);
    assert!(result.contains(r#""max-lines":"#));
    assert!(result.contains(r#"eqeqeq: ["error", "always"]"#));
    assert!(result.contains(r#""no-restricted-imports""#));
    assert!(result.contains(r#""no-param-reassign": "error""#));
    assert!(result.contains(r#""no-void": "error""#));
    assert!(result.contains(r#""@typescript-eslint/no-explicit-any": "error""#));
    assert!(result.contains(r#""@typescript-eslint/only-throw-error": "error""#));
    assert!(result.contains(r#""@typescript-eslint/naming-convention""#));
    assert!(result.contains(r#""max-depth": ["error", 4]"#));
    assert!(result.contains(r#""max-params": ["error", 4]"#));
}

#[test]
fn config_has_restricted_imports() {
    let result = build_eslint_config(false, false);
    for pkg in &[
        "axios",
        "lodash",
        "moment",
        "uuid",
        "nanoid",
        "pg",
        "express",
        "classnames",
        "winston",
        "request",
        "got",
        "superagent",
        "node-fetch",
        "isomorphic-fetch",
        "underscore",
    ] {
        assert!(
            result.contains(&format!(r#"name: "{pkg}""#)),
            "missing: {pkg}"
        );
    }
}

#[test]
fn config_has_test_relaxation() {
    let result = build_eslint_config(false, false);
    assert!(result.contains("**/*.test.ts"));
    assert!(result.contains("**/__tests__/**"));
    assert!(result.contains(r#""max-params": "off""#));
    assert!(result.contains(r#""sonarjs/no-duplicate-string": "off""#));
}
