use super::Module;

/// The canonical cspell.json content, entirely static.
const CSPELL_JSON: &str = r#"{
  "$schema": "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json",
  "_comment": "GENERATED by guardrail3 — do not edit manually",
  "version": "0.2",
  "language": "en",
  "ignorePaths": [
    "node_modules",
    ".next",
    "dist",
    "target",
    "coverage",
    ".plans",
    ".worklogs",
    "drizzle",
    "*.generated.*",
    ".claude",
    "pnpm-lock.yaml",
    "Cargo.lock"
  ],
  "words": []
}
"#;

pub const CSPELL_CONFIG: Module = Module {
    name: "canonical/cspell",
    description: "Standard cspell.json spell-checking configuration",
    content: CSPELL_JSON,
};

/// Build a cspell.json configuration for spell checking.
pub fn build_cspell_config() -> String {
    CSPELL_JSON.to_owned()
}

#[cfg(test)]
#[path = "cspell_tests.rs"]
mod cspell_tests;
