// ---------------------------------------------------------------------------
// ESLint config builder — generates a complete eslint.config.mjs
// ---------------------------------------------------------------------------

const HEADER: &str = "\
// GENERATED by guardrail3 — do not edit manually
// @ts-check
";

const IMPORTS_BASE: &str = r#"
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import unicorn from "eslint-plugin-unicorn";
import regexp from "eslint-plugin-regexp";
import sonarjs from "eslint-plugin-sonarjs";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
"#;

const IMPORTS_CONTENT: &str = r#"import jsxA11y from "eslint-plugin-jsx-a11y";
import tailwindBan from "eslint-plugin-tailwind-ban";
"#;

const IMPORTS_SERVICE: &str = r#"import boundaries from "eslint-plugin-boundaries";
"#;

const CONFIG_OPEN: &str = r"
export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
";

const LANGUAGE_OPTIONS: &str = r"  {
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
  },
";

const GLOBAL_IGNORES: &str = r#"  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/target/**",
      "**/drizzle/**",
      "**/*.generated.*",
      "**/.plans/**",
      "**/.worklogs/**",
      "**/coverage/**",
      "**/.claude/**",
    ],
  },
"#;

const UNICORN_SECTION: &str = r#"  {
    ...unicorn.configs["flat/recommended"],
    rules: {
      ...unicorn.configs["flat/recommended"].rules,
      "unicorn/no-null": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/filename-case": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-array-callback-reference": "off",
      "unicorn/no-useless-undefined": "off",
      "unicorn/prefer-module": "off",
      "unicorn/no-keyword-prefix": "warn",
      "unicorn/no-unused-properties": "warn",
      "unicorn/require-post-message-target-origin": "error",
      "unicorn/no-anonymous-default-export": "error",
    },
  },
"#;

const REGEXP_SECTION: &str = r#"  {
    ...regexp.configs["flat/recommended"],
    rules: {
      ...regexp.configs["flat/recommended"].rules,
      "regexp/require-unicode-regexp": "error",
      "regexp/require-unicode-sets-regexp": "error",
      "regexp/prefer-named-capture-group": "error",
      "regexp/prefer-named-backreference": "error",
      "regexp/prefer-result-array-groups": "error",
      "regexp/no-misleading-capturing-group": "error",
    },
  },
"#;

const SONARJS_SECTION: &str = r#"  {
    plugins: { sonarjs },
    rules: {
      "sonarjs/cognitive-complexity": "error",
      "sonarjs/no-identical-functions": "error",
      "sonarjs/no-all-duplicated-branches": "error",
      "sonarjs/no-duplicated-branches": "error",
      "sonarjs/no-collapsible-if": "error",
      "sonarjs/no-identical-conditions": "error",
      "sonarjs/no-identical-expressions": "error",
      "sonarjs/no-inverted-boolean-check": "error",
      "sonarjs/no-redundant-boolean": "error",
      "sonarjs/prefer-single-boolean-return": "error",
      "sonarjs/no-gratuitous-expressions": "error",
      "sonarjs/no-invariant-returns": "error",
      "sonarjs/no-collection-size-mischeck": "error",
      "sonarjs/no-empty-collection": "error",
      "sonarjs/no-element-overwrite": "error",
      "sonarjs/no-unused-collection": "error",
      "sonarjs/no-use-of-empty-return-value": "error",
      "sonarjs/no-nested-switch": "error",
      "sonarjs/no-nested-template-literals": "error",
      "sonarjs/no-redundant-jump": "error",
      "sonarjs/expression-complexity": "error",
      "sonarjs/no-async-constructor": "error",
      "sonarjs/no-hook-setter-in-body": "error",
      "sonarjs/no-useless-react-setstate": "error",
    },
  },
"#;

const REACT_SECTION: &str = r#"  {
    plugins: { react, "react-hooks": reactHooks },
    rules: {
      "react/no-unstable-nested-components": "error",
      "react/no-danger": "error",
      "react/iframe-missing-sandbox": "error",
      "react/no-array-index-key": "error",
      "react/button-has-type": "error",
      "react/jsx-no-script-url": "error",
      "react/jsx-no-constructed-context-values": "error",
      "react/no-invalid-html-attribute": "error",
      "react/hook-use-state": "error",
      "react/checked-requires-onchange-or-readonly": "error",
      "react/jsx-no-leaked-render": ["error", { validStrategies: ["ternary"] }],
    },
  },
"#;

const CORE_RULES_SECTION: &str = r#"  {
    rules: {
      "max-lines": ["error", { max: 400, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["warn", { max: 100, skipBlankLines: true, skipComments: true }],
      complexity: ["warn", 25],
      "no-console": ["error", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always"],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "axios", message: "Use fetch or a shared HTTP client" },
            { name: "lodash", message: "Use native JS methods or es-toolkit" },
            { name: "moment", message: "Use date-fns or Temporal" },
            { name: "uuid", message: "Use crypto.randomUUID()" },
            { name: "nanoid", message: "Use crypto.randomUUID()" },
            { name: "pg", message: "Use drizzle-orm with postgres.js driver" },
            { name: "express", message: "Use Next.js API routes or Hono" },
            { name: "classnames", message: "Use clsx or cn() utility" },
            { name: "winston", message: "Use pino" },
            { name: "request", message: "Deprecated — use fetch" },
            { name: "got", message: "Use fetch" },
            { name: "superagent", message: "Use fetch" },
            { name: "node-fetch", message: "Use native fetch (Node 18+)" },
            { name: "isomorphic-fetch", message: "Use native fetch (Node 18+)" },
            { name: "underscore", message: "Use native JS methods or es-toolkit" },
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        { name: "process", message: "Use env() from @/lib/env instead of process.env" },
      ],
      "no-param-reassign": "error",
      "no-return-assign": "error",
      "prefer-template": "error",
      "object-shorthand": "error",
      "no-sequences": "error",
      "no-void": "error",
    },
  },
"#;

const TS_STRICT_RULES_SECTION: &str = r#"  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/strict-boolean-expressions": "warn",
      "@typescript-eslint/explicit-function-return-type": [
        "warn",
        { allowExpressions: true, allowTypedFunctionExpressions: true },
      ],
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/explicit-module-boundary-types": "warn",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "@typescript-eslint/no-unnecessary-condition": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/no-deprecated": "warn",
      "@typescript-eslint/restrict-template-expressions": "error",
      "@typescript-eslint/only-throw-error": "error",
      "no-empty": "error",
      "@typescript-eslint/no-shadow": "error",
      "max-depth": ["error", 4],
      "max-params": ["error", 4],
      "max-nested-callbacks": ["error", 3],
      "@typescript-eslint/no-confusing-void-expression": "error",
      "@typescript-eslint/naming-convention": [
        "warn",
        {
          selector: "default",
          format: ["camelCase", "PascalCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: "variable",
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
        },
        { selector: "typeLike", format: ["PascalCase"] },
      ],
      "@typescript-eslint/method-signature-style": ["error", "property"],
    },
  },
"#;

const TEST_RELAXATION_SECTION: &str = r#"  {
    files: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
      "**/__tests__/**",
    ],
    rules: {
      "max-params": "off",
      "@typescript-eslint/naming-convention": "off",
      "sonarjs/cognitive-complexity": "off",
      "sonarjs/no-identical-functions": "off",
      "sonarjs/no-duplicate-string": "off",
    },
  },
"#;

const CONTENT_A11Y_SECTION: &str = r#"  {
    ...jsxA11y.flatConfigs.strict,
    rules: {
      ...jsxA11y.flatConfigs.strict.rules,
      "jsx-a11y/control-has-associated-label": "warn",
    },
  },
"#;

const CONTENT_TAILWIND_BAN_SECTION: &str = r#"  {
    plugins: { "tailwind-ban": tailwindBan },
    rules: {
      "tailwind-ban/ban-classes": [
        "error",
        { denyList: ["bg-", "text-", "border-", "p-", "m-", "w-", "h-"] },
      ],
    },
  },
"#;

const SERVICE_BOUNDARIES_SECTION: &str = r#"  {
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        { type: "domain", pattern: "src/domain/**" },
        { type: "app", pattern: "src/app/**" },
        { type: "adapters", pattern: "src/adapters/**" },
        { type: "lib", pattern: "src/lib/**" },
      ],
    },
    rules: {
      // Customize boundary rules per project
      "boundaries/element-types": "warn",
    },
  },
"#;

const SERVICE_ROUTE_WRAPPER_SECTION: &str = r#"  {
    // Project-specific: flag route handlers not wrapped with withBody/withRoute
    // Uncomment and customize the selector for your framework:
    // rules: {
    //   "no-restricted-syntax": [
    //     "error",
    //     {
    //       selector: "ExportDefaultDeclaration > FunctionDeclaration",
    //       message: "Route handlers must use withBody/withRoute wrapper",
    //     },
    //   ],
    // },
  },
"#;

const CONFIG_CLOSE: &str = ");\n";

/// Build a complete eslint.config.mjs with all guardrail plugins and rules.
pub fn build_eslint_config(has_content_app: bool, has_service_app: bool) -> String {
    let mut config = String::with_capacity(8192);

    // Header
    config.push_str(HEADER);

    // Imports
    config.push_str(IMPORTS_BASE);
    if has_content_app {
        config.push_str(IMPORTS_CONTENT);
    }
    if has_service_app {
        config.push_str(IMPORTS_SERVICE);
    }

    // Config body
    config.push_str(CONFIG_OPEN);
    config.push_str(LANGUAGE_OPTIONS);
    config.push_str(GLOBAL_IGNORES);
    config.push_str(UNICORN_SECTION);
    config.push_str(REGEXP_SECTION);
    config.push_str(SONARJS_SECTION);
    config.push_str(REACT_SECTION);
    config.push_str(CORE_RULES_SECTION);
    config.push_str(TS_STRICT_RULES_SECTION);
    config.push_str(TEST_RELAXATION_SECTION);

    // Conditional: content-app sections
    if has_content_app {
        config.push_str(CONTENT_A11Y_SECTION);
        config.push_str(CONTENT_TAILWIND_BAN_SECTION);
    }

    // Conditional: service-app sections
    if has_service_app {
        config.push_str(SERVICE_BOUNDARIES_SECTION);
        config.push_str(SERVICE_ROUTE_WRAPPER_SECTION);
    }

    // Close
    config.push_str(CONFIG_CLOSE);

    config
}

#[cfg(test)]
#[path = "eslint_tests.rs"]
mod eslint_tests;
