/// The embedded `GUARDRAIL3_GUIDE.md` content.
pub const GUIDE_CONTENT: &str = r#"# GUARDRAIL3 GUIDE

> This file was generated by `guardrail3 guide`. Do not edit manually.
> Regenerate after updating guardrail3: `guardrail3 guide`

## Command Reference

### Rust

```text
guardrail3 rs init [PATH] --profile <service|library> [--force]
guardrail3 rs generate [PATH]
guardrail3 rs validate [PATH] [--family <NAME> ...] [--staged|--dirty|--commits N|--files ...]
guardrail3 rs check [PATH]
guardrail3 rs hooks-install [PATH]
guardrail3 rs list-modules
guardrail3 rs show-module <NAME>
```

Rust validate families:

```text
arch
fmt
toolchain
clippy
deny
cargo
code
hexarch
deps
garde
test
release
hooks-shared
hooks-rs
```

`hooks-rs` implies `hooks-shared`.

Examples:

```text
guardrail3 rs validate .
guardrail3 rs validate . --family arch
guardrail3 rs validate . --family hexarch
guardrail3 rs validate . --family code --family garde --staged
guardrail3 rs validate . --family release --thorough
```

### TypeScript

```text
guardrail3 ts init [PATH] [--force]
guardrail3 ts generate [PATH]
guardrail3 ts validate [PATH] [--staged|--dirty|--commits N|--files ...]
guardrail3 ts hooks-install [PATH]
guardrail3 ts hooks-validate [PATH]
```

## Config File

Only `generate` / `check` depend on `guardrail3.toml`. Rust validate also reads it for family enable/disable policy and fails closed if `[rust.checks]` is malformed.

### Rust family toggles

```toml
[rust.checks]
arch = true
fmt = true
toolchain = true
clippy = true
deny = true
cargo = true
code = true
hexarch = true
deps = true
garde = true
test = true
release = true
hooks_shared = true
hooks_rs = true
```

Per-app and package overrides use the scoped family names only. `arch` stays global-only under `[rust.checks]`:

```toml
[rust.apps.my_api.checks]
hexarch = true
garde = false

[rust.packages.checks]
code = true
test = true
release = false
```

Removed Rust check keys:

```toml
architecture
tests
hooks
```

Use:

```toml
hexarch
test
hooks_shared
hooks_rs
```

## Profiles

`service`
- For binaries and services that do I/O.
- Services typically live under `apps/` and use hex arch.

`library`
- For shared packages with no uncontrolled I/O.
- Libraries typically live under `packages/` and use `allowed_deps`.

## Architecture Convention

Rust services:

```text
apps/my-api/
  crates/
    domain/
    ports/
      inbound/
      outbound/
    app/
    adapters/
      inbound/api/
      outbound/
```

Rust libraries:

```text
packages/my-lib/
```

TypeScript services:

```text
apps/my-app/src/
  modules/
    domain/
    ports/
      inbound/
      outbound/
    application/
    adapters/
      inbound/api/
      outbound/
```

## Generated Files

Rust generation can write:

```text
clippy.toml
deny.toml
rustfmt.toml
rust-toolchain.toml
release-plz.toml
cliff.toml
.githooks/pre-commit
```

TypeScript generation can write:

```text
eslint.config.mjs
tsconfig.base.json
.npmrc
.jscpd.json
.githooks/pre-commit
```

## Output

`guardrail3 rs validate` emits only `RS-*` and `HOOK-*` findings.

JSON output shape:

```json
{
  "project": "<path>",
  "stacks": ["Rust"],
  "sections": [
    {
      "name": "hexarch",
      "results": [
        {
          "id": "RS-HEXARCH-01",
          "severity": "error|warn|info",
          "title": "<short title>",
          "message": "<detailed message>",
          "file": "<absolute path or null>",
          "file_relative": "<relative path or null>",
          "line": "<line number or null>",
          "inventory": true|false
        }
      ]
    }
  ],
  "summary": {
    "errors": 0,
    "warnings": 0,
    "info": 0
  }
}
```
"#;
