use super::Module;

pub const RELEASE_PLZ_TOML: Module = Module {
    name: "release/release-plz",
    description: "Standard release-plz.toml configuration for automated semver releases",
    content: r#"# =============================================================================
# release-plz configuration -- GENERATED by guardrail3
# DO NOT EDIT -- regenerate with: guardrail3 generate
# =============================================================================

[workspace]
changelog_config = "cliff.toml"
git_release_enable = true
release_always = false

# One entry per publishable package
[[package]]
name = "your-crate-name"
publish = true

# Add more [[package]] entries for workspaces with multiple publishable crates
"#,
};

pub const CLIFF_TOML: Module = Module {
    name: "release/cliff",
    description: "Standard cliff.toml changelog configuration for git-cliff",
    content: r#"# =============================================================================
# git-cliff changelog configuration -- GENERATED by guardrail3
# DO NOT EDIT -- regenerate with: guardrail3 generate
# =============================================================================

[changelog]
header = """
# Changelog\n
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous" },
]
"#,
};
