use g3rs_code_source_checks_runtime as _;

mod common;

#[cfg(feature = "checks")]
pub mod always_true_cfg_attr_bypass;
#[cfg(feature = "checks")]
pub mod cfg_attr_allow_inventory;
#[cfg(feature = "checks")]
pub mod crate_level_allow;
#[cfg(feature = "checks")]
pub mod deny_forbid_without_reason;
#[cfg(feature = "checks")]
pub mod direct_fs_usage;
#[cfg(feature = "checks")]
pub mod extern_allow;
#[cfg(feature = "checks")]
pub mod fs_glob_import;
#[cfg(feature = "checks")]
pub mod garde_skip_with_comment;
#[cfg(feature = "checks")]
pub mod garde_skip_without_comment;
#[cfg(feature = "checks")]
pub mod generic_parameter_cap;
#[cfg(feature = "checks")]
pub mod impl_allow_blast_radius;
#[cfg(feature = "checks")]
pub mod include_bypass;
#[cfg(feature = "checks")]
pub mod input_failures;
#[cfg(feature = "checks")]
pub mod item_level_allow_with_reason;
#[cfg(feature = "checks")]
pub mod item_level_allow_without_reason;
#[cfg(feature = "checks")]
pub mod large_trait_surface;
#[cfg(feature = "checks")]
pub mod large_type_inventory;
#[cfg(feature = "checks")]
pub mod many_use_imports;
#[cfg(feature = "checks")]
pub mod panic_macro;
#[cfg(feature = "checks")]
pub mod path_attr_with_reason;
#[cfg(feature = "checks")]
pub mod public_struct_named_fields;
#[cfg(feature = "checks")]
pub mod public_weak_error_forms;
#[cfg(feature = "checks")]
pub mod run;
#[cfg(feature = "checks")]
pub mod string_dispatch_cap;
#[cfg(feature = "checks")]
pub mod test_expect_message_quality;
#[cfg(feature = "checks")]
pub mod todo_macros;
#[cfg(feature = "checks")]
pub mod too_many_effective_code_lines;
#[cfg(feature = "checks")]
pub mod too_many_use_imports;
#[cfg(feature = "checks")]
pub mod unused_crate_dependencies_allow;
