use g3rs_code_source_checks_runtime as _;

mod common;

#[cfg(feature = "checks")]
pub mod rs_code_ast_01_crate_level_allow;
#[cfg(feature = "checks")]
pub mod rs_code_ast_02_unused_crate_dependencies_allow;
#[cfg(feature = "checks")]
pub mod rs_code_ast_03_item_level_allow_without_reason;
#[cfg(feature = "checks")]
pub mod rs_code_ast_04_item_level_allow_with_reason;
#[cfg(feature = "checks")]
pub mod rs_code_ast_05_garde_skip_without_comment;
#[cfg(feature = "checks")]
pub mod rs_code_ast_06_garde_skip_with_comment;
#[cfg(feature = "checks")]
pub mod rs_code_ast_08_cfg_attr_allow_inventory;
#[cfg(feature = "checks")]
pub mod rs_code_ast_09_too_many_effective_code_lines;
#[cfg(feature = "checks")]
pub mod rs_code_ast_10_too_many_use_imports;
#[cfg(feature = "checks")]
pub mod rs_code_ast_11_many_use_imports;
#[cfg(feature = "checks")]
pub mod rs_code_ast_13_todo_macros;
#[cfg(feature = "checks")]
pub mod rs_code_ast_15_direct_fs_usage;
#[cfg(feature = "checks")]
pub mod rs_code_ast_16_panic_macro;
#[cfg(feature = "checks")]
pub mod rs_code_ast_17_impl_allow_blast_radius;
#[cfg(feature = "checks")]
pub mod rs_code_ast_18_always_true_cfg_attr_bypass;
#[cfg(feature = "checks")]
pub mod rs_code_ast_19_large_type_inventory;
#[cfg(feature = "checks")]
pub mod rs_code_ast_20_extern_allow;
#[cfg(feature = "checks")]
pub mod rs_code_ast_21_fs_glob_import;
#[cfg(feature = "checks")]
pub mod rs_code_ast_22_deny_forbid_without_reason;
#[cfg(feature = "checks")]
pub mod rs_code_ast_23_include_bypass;
#[cfg(feature = "checks")]
pub mod rs_code_ast_24_path_attr_with_reason;
#[cfg(feature = "checks")]
pub mod rs_code_ast_29_large_trait_surface;
#[cfg(feature = "checks")]
pub mod rs_code_ast_30_input_failures;
#[cfg(feature = "checks")]
pub mod rs_code_ast_31_public_struct_named_fields;
#[cfg(feature = "checks")]
pub mod rs_code_ast_32_test_expect_message_quality;
#[cfg(feature = "checks")]
pub mod rs_code_ast_33_public_weak_error_forms;
#[cfg(feature = "checks")]
pub mod rs_code_ast_34_generic_parameter_cap;
#[cfg(feature = "checks")]
pub mod rs_code_ast_36_string_dispatch_cap;
