mod rs_deny_config_06_multiple_versions_floor;
mod rs_deny_config_07_highlight_inventory;
mod rs_deny_config_08_allow_wildcard_paths;
mod rs_deny_config_09_wildcards_inventory;
mod rs_deny_config_16_tokio_full_ban;
mod rs_deny_config_17_extra_feature_bans_inventory;
mod rs_deny_config_20_duplicate_entries;
mod run;

pub(crate) use run::check;
