profile = "library"

allowed_deps = [
  "cargo-config-toml-parser",
  "cargo-toml-parser",
  "g3rs-cargo-config-checks",
  "g3rs-cargo-filetree-checks",
  "g3rs-cargo-ingestion-runtime",
  "g3rs-cargo-ingestion-types",
  "g3rs-cargo-types",
  "g3-workspace-crawl",
  "glob",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "toml",
]

[checks]
garde = false
