profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "g3rs-fmt-types",
  "guardrail3-check-types",
  "guardrail3-reason-policy",
  "rust-toolchain-toml-parser",
  "rustfmt-toml-parser",
  "toml",
]

[checks]
garde = false
