profile = "library"

allowed_deps = [
  "cargo-toml-parser",
  "clippy-toml-parser",
  "g3rs-garde-config-checks",
  "g3rs-garde-config-checks-assertions",
  "g3rs-garde-source-checks",
  "g3rs-garde-source-checks-types",
  "g3rs-garde-types",
  "guardrail3-check-types",
  "g3-workspace-crawl",
  "g3rs-toml-parser",
  "proc-macro2",
  "quote",
  "syn",
  "tempfile",
]

[checks]
garde = false
