#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore


REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_LEDGER = REPO_ROOT / "behavior" / "migration" / "g3rs-test-fixture-ledger.toml"
OUTPUT_LEDGER = REPO_ROOT / "behavior" / "migration" / "g3rs-kept-test-disposition.toml"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rows = classify_rows()
    output = render_ledger(rows)
    if args.check:
        current = OUTPUT_LEDGER.read_text(encoding="utf-8")
        if current != output:
            print("kept test disposition ledger is not classified from current sources")
            return 1
        print("kept test disposition ledger classification is current")
        return 0

    OUTPUT_LEDGER.write_text(output, encoding="utf-8")
    counts = Counter(row["disposition"] for row in rows)
    print(
        "classified kept test dispositions "
        + " ".join(f"{status}:{count}" for status, count in sorted(counts.items()))
    )
    return 0


def classify_rows() -> list[dict[str, Any]]:
    ledger = load_toml(SOURCE_LEDGER)
    rows = ledger.get("test", [])
    output: list[dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, dict) or row.get("status") != "kept_compile_contract":
            continue
        test_path = str(row["test_path"])
        test_name = str(row["test_name"])
        disposition, reason = classify_row(test_path)
        output.append(
            {
                "test_path": test_path,
                "test_name": test_name,
                "line": int(row["line"]),
                "disposition": disposition,
                "reason": reason,
            }
        )
    return output


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as file:
        return tomllib.load(file)


def classify_row(test_path: str) -> tuple[str, str]:
    if "/contract_tests/" in test_path or "-hook-contract/" in test_path:
        return (
            "keep_public_api_contract",
            "hook-contract crates define public policy contracts that should remain compile/API tests until replaced by API snapshots",
        )
    if test_path.startswith("apps/guardrail3-rs/crates/io/inbound/cli/"):
        return (
            "needs_cli_contract_replay",
            "CLI parse and run behavior should be captured by command stdout/stderr/exit replay",
        )
    if test_path.startswith("apps/guardrail3-rs/crates/io/outbound/report/"):
        return (
            "needs_renderer_replay",
            "report formatting behavior should be captured by renderer output snapshots",
        )
    if test_path.startswith("apps/guardrail3-rs/crates/logic/validate-command/"):
        return (
            "needs_validate_command_replay",
            "validate-command behavior needs CLI command replay for cargo gates, staged paths, and family selection",
        )
    if test_path.startswith("apps/guardrail3-rs/crates/logic/family-runner-process/"):
        return (
            "needs_family_runner_replay",
            "family runner behavior needs runner-level replay for hook injection and family contract aggregation",
        )
    if "/g3rs-" in test_path and "-ingestion/" in test_path:
        return (
            "needs_ingestion_replay",
            "ingestion behavior needs normalized family-fact replay rather than direct rule finding replay",
        )
    if "/run_tests/" in test_path:
        return (
            "needs_family_runner_replay",
            "family run behavior needs runner-level replay for dispatch, aggregation, and inactive-family behavior",
        )
    if is_rule_sidecar_behavior(test_path):
        return (
            "needs_fixture_or_golden_backfill",
            "direct rule-sidecar behavior should be represented by fixture output or a rule-level golden snapshot",
        )
    return (
        "needs_family_runner_replay",
        "remaining non-ingestion test behavior is runner or aggregation behavior unless a narrower replay harness supersedes it",
    )


def is_rule_sidecar_behavior(test_path: str) -> bool:
    path = REPO_ROOT / test_path
    if "/rule_tests/" in test_path:
        return True
    for parent in path.parents:
        name = parent.name
        if not name.endswith("_tests"):
            continue
        sibling_rule = parent.parent / f"{name.removesuffix('_tests')}.rs"
        if sibling_rule.is_file():
            return True
    return False


def render_ledger(rows: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by scripts/behavior/classify-kept-test-dispositions.py",
        "# Rows come from behavior/migration/g3rs-test-fixture-ledger.toml where status = \"kept_compile_contract\".",
        "",
    ]
    for row in rows:
        lines.append("[[test]]")
        for key in ("test_path", "test_name", "line", "disposition", "reason"):
            lines.append(f"{key} = {toml_value(row[key])}")
        lines.append("")
    return "\n".join(lines)


def toml_value(value: object) -> str:
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise TypeError(f"unsupported TOML value: {value!r}")


if __name__ == "__main__":
    sys.exit(main())
