#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROOTS = ("packages/rs", "apps/guardrail3-rs")
TEST_ATTR_RE = re.compile(r"^\s*#\s*\[\s*test\s*\]")
FN_RE = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--format", choices=("json", "toml-ledger"), default="json")
    parser.add_argument("roots", nargs="*", default=list(DEFAULT_ROOTS))
    args = parser.parse_args()

    tests = discover_tests(args.roots)
    if args.format == "json":
        print(json.dumps({"tests": tests}, indent=2, sort_keys=True))
        return 0
    print_toml_ledger(tests)
    return 0


def discover_tests(raw_roots: list[str]) -> list[dict[str, object]]:
    tests: list[dict[str, object]] = []
    for raw_root in raw_roots:
        root = REPO_ROOT / raw_root
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.rs")):
            if should_skip(path):
                continue
            tests.extend(extract_tests(path))
    return sorted(tests, key=lambda row: (str(row["test_path"]), str(row["test_name"]), int(row["line"])))


def should_skip(path: Path) -> bool:
    rel_parts = path.relative_to(REPO_ROOT).parts
    return any(part in {"target", ".cargo-target", "legacy"} for part in rel_parts)


def extract_tests(path: Path) -> list[dict[str, object]]:
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    tests: list[dict[str, object]] = []
    pending_test_line: int | None = None
    rel_path = path.relative_to(REPO_ROOT).as_posix()
    for index, line in enumerate(lines, start=1):
        if TEST_ATTR_RE.match(line):
            pending_test_line = index
            continue
        if pending_test_line is None:
            continue
        match = FN_RE.search(line)
        if match:
            tests.append(
                {
                    "test_path": rel_path,
                    "test_name": match.group(1),
                    "line": pending_test_line,
                }
            )
            pending_test_line = None
            continue
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        if stripped.startswith("#["):
            continue
        if pending_test_line is not None and index > pending_test_line and is_attribute_continuation(lines, index):
            continue
        if stripped:
            pending_test_line = None
    return tests


def is_attribute_continuation(lines: list[str], one_based_index: int) -> bool:
    open_brackets = 0
    for line in reversed(lines[: one_based_index - 1]):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        open_brackets += stripped.count("]") - stripped.count("[")
        if stripped.startswith("#["):
            return open_brackets < 0
    return False


def print_toml_ledger(tests: list[dict[str, object]]) -> None:
    print("# Generated by scripts/behavior/list-rust-tests.py --format toml-ledger")
    print("# Classify rows before using --strict verification.")
    print()
    for row in tests:
        print("[[test]]")
        print(f"test_path = {toml_string(str(row['test_path']))}")
        print(f"test_name = {toml_string(str(row['test_name']))}")
        print(f"line = {row['line']}")
        print('status = "unclassified"')
        print()


def toml_string(value: str) -> str:
    return json.dumps(value)


if __name__ == "__main__":
    sys.exit(main())
