profile = "library"

allowed_deps = [
  "g3rs-arch-file-tree-checks-assertions",
  "g3rs-arch-file-tree-checks-runtime",
  "g3rs-arch-types",
  "guardrail3-check-types",
  "g3rs-toml-parser",
]

[checks]
garde = false
