pub mod hook_shared_07_modular_scripts_inventory;
pub mod hook_shared_08_pre_commit_file_size_inventory;
pub mod hook_shared_09_local_override_inventory;
pub mod hook_shared_12_modular_scripts_executable;
pub mod hook_shared_17_execution_trust;
