profile = "library"

allowed_deps = [
  "eslint-config-parser",
  "eslint-directive-parser",
  "g3-workspace-crawl",
  "g3rs-workspace-crawl",
  "g3ts-astro-check-support",
  "g3ts-astro-mdx-types",
  "globset",
  "guardrail3-rs-toml-parser",
  "package-json-parser",
  "package-script-command-parser",
  "serde_json",
]

[checks]
garde = false
