use guardrail3_app_rs_family_deny as _;

mod common;

#[cfg(feature = "checks")]
pub mod facts;
#[path = "coverage/rs_deny_01_coverage.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_01_coverage;
#[path = "coverage/rs_deny_03_shadowing.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_03_shadowing;
#[path = "advisories/rs_deny_04_deprecated_advisories.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_04_deprecated_advisories;
#[path = "advisories/rs_deny_05_advisories_baseline.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_05_advisories_baseline;
#[path = "advisories/rs_deny_06_stricter_advisories_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_06_stricter_advisories_inventory;
#[path = "advisories/rs_deny_07_graph_all_features.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_07_graph_all_features;
#[path = "advisories/rs_deny_08_graph_no_default_features.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_08_graph_no_default_features;
#[path = "bans/rs_deny_09_ban_baseline_complete.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_09_ban_baseline_complete;
#[path = "bans/rs_deny_10_multiple_versions_floor.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_10_multiple_versions_floor;
#[path = "bans/rs_deny_11_highlight_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_11_highlight_inventory;
#[path = "bans/rs_deny_12_allow_wildcard_paths.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_12_allow_wildcard_paths;
#[path = "bans/rs_deny_13_wildcards_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_13_wildcards_inventory;
#[path = "licenses/rs_deny_14_license_allow_baseline.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_14_license_allow_baseline;
#[path = "licenses/rs_deny_15_confidence_threshold.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_15_confidence_threshold;
#[path = "licenses/rs_deny_16_copyleft_allowlist.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_16_copyleft_allowlist;
#[path = "licenses/rs_deny_17_license_exceptions_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_17_license_exceptions_inventory;
#[path = "sources/rs_deny_18_unknown_sources_policy.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_18_unknown_sources_policy;
#[path = "sources/rs_deny_19_allow_registry_baseline.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_19_allow_registry_baseline;
#[path = "sources/rs_deny_20_allow_git_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_20_allow_git_inventory;
#[path = "bans/rs_deny_21_tokio_full_ban.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_21_tokio_full_ban;
#[path = "bans/rs_deny_22_extra_feature_bans_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_22_extra_feature_bans_inventory;
#[path = "sources/rs_deny_23_skip_hygiene.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_23_skip_hygiene;
#[path = "sources/rs_deny_24_ignore_hygiene.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_24_ignore_hygiene;
#[path = "sources/rs_deny_25_allow_override_channel.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_25_allow_override_channel;
#[path = "bans/rs_deny_26_ban_reason_inventory.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_26_ban_reason_inventory;
#[path = "bans/rs_deny_27_duplicate_entries.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_27_duplicate_entries;
#[path = "sources/rs_deny_28_unknown_keys.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_28_unknown_keys;
#[path = "sources/rs_deny_29_ignore_accumulation.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_29_ignore_accumulation;
#[path = "sources/rs_deny_30_wrappers.rs"]
#[cfg(feature = "checks")]
pub mod rs_deny_30_wrappers;
