profile = "library"

allowed_deps = [
  "g3-guardrail-toml-types",
  "cargo-config-toml-parser",
  "cargo-toml-parser",
  "g3rs-cargo-types",
  "guardrail3-check-types",
  "g3rs-toml-parser",
  "guardrail3-reason-policy",
]

[checks]
garde = false
