use super::Module;

pub const RUSTFMT: Module = Module {
    name: "canonical/rustfmt",
    description: "Standard rustfmt.toml configuration",
    content: r#"# =============================================================================
# rustfmt configuration -- GENERATED by guardrail3
# DO NOT EDIT -- regenerate with: guardrail3 generate
# =============================================================================

# --- Stable settings (work with any rustfmt) ---------------------------------

edition = "2024"
max_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true

# --- Nightly-only settings ----------------------------------------------------
# These require nightly rustfmt: cargo +nightly fmt
# On stable rustfmt they will produce an error. Uncomment only if your
# CI/local workflow uses nightly rustfmt.
#
# Check compatibility with: rustfmt --version
# Nightly status tracking: https://rust-lang.github.io/rustfmt/

# imports_granularity = "Crate"           # Merge imports from the same crate into one `use` block
# group_imports = "StdExternalCrate"      # Three-tier ordering: std -> external crates -> internal modules
# format_code_in_doc_comments = true      # Run rustfmt on code blocks inside /// doc comments
# format_strings = true                   # Wrap long string literals
# overflow_delimited_expr = true          # Allow closures/arrays to overflow for readability
"#,
};

pub const RUST_TOOLCHAIN: Module = Module {
    name: "canonical/rust-toolchain",
    description: "Standard rust-toolchain.toml configuration",
    content: r#"[toolchain]
channel = "stable"
components = ["clippy", "rustfmt"]
"#,
};

pub const CARGO_LINTS: Module = Module {
    name: "canonical/cargo-lints",
    description: "Recommended [workspace.lints] for Cargo.toml",
    content: r#"[workspace.lints.rust]
warnings = "deny"                    # Deny all unlisted warnings (equivalent to -Dwarnings)
unsafe_code = "forbid"
dead_code = "deny"
unused_results = "deny"
unused_crate_dependencies = "deny"
missing_debug_implementations = "warn"  # Helps catch types that are hard to debug

[workspace.lints.clippy]
# -- Groups --
# Priority -1 ensures group-level settings are overridden by
# the specific lint settings below (higher priority wins).
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
# Experimental but useful catches. May need per-lint #[allow] for false positives.
nursery = { level = "deny", priority = -1 }

# -- Error handling (no silent crashes) --
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unimplemented = "deny"
todo = "deny"

# -- Output discipline --
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"

# -- Disallowed methods/types (enforces clippy.toml) --
disallowed_methods = "deny"
disallowed_types = "deny"

# -- Panic backdoors (bypass unwrap/expect/panic bans) --
indexing_slicing = "deny"          # vec[i] panics -- use .get(i) instead
string_slice = "deny"             # &s[0..5] panics on non-ASCII -- use .get() or .chars()
arithmetic_side_effects = "deny"  # a + b overflows -- use .checked_add() / .saturating_add()

# -- Variable hygiene --
shadow_unrelated = "deny"          # let x = 5; let x = "str"; -- use different name
missing_assert_message = "deny"    # assert!(x) -- require assert!(x, "reason")

# -- Encapsulation --
partial_pub_fields = "deny"        # struct with mix of pub/private fields -- all or nothing

# -- Allocation awareness --
str_to_string = "deny"
implicit_clone = "deny"

# -- Type safety --
as_conversions = "deny"
float_cmp = "deny"
lossy_float_literal = "deny"

# -- Pattern exhaustiveness --
wildcard_enum_match_arm = "deny"
rest_pat_in_fully_bound_structs = "deny"

# -- Size guards --
large_stack_arrays = "deny"

# -- Code hygiene --
needless_pass_by_value = "deny"
redundant_else = "deny"
large_futures = "deny"

# -- Idiomatic style --
semicolon_if_nothing_returned = "deny"
redundant_closure_for_method_calls = "deny"
map_unwrap_or = "deny"
verbose_file_reads = "deny"

# -- Pedantic/nursery overrides --
# Genuinely unavoidable style preferences
module_name_repetitions = "allow"         # UserError in user module is fine
must_use_candidate = "allow"              # Not every function needs #[must_use]
option_if_let_else = "allow"              # if let Some(x) is often clearer than map_or
empty_line_after_doc_comments = "allow"   # Stylistic, not worth enforcing
single_match_else = "allow"              # match with else is sometimes clearer than if let
ref_option_ref = "allow"                 # &Option<&T> is valid in function signatures
trivially_copy_pass_by_ref = "allow"     # &bool, &i32 in params is fine
multiple_crate_versions = "allow"        # Defer to deny.toml for duplicate version checking
"#,
};

pub const NPMRC: Module = Module {
    name: "canonical/npmrc",
    description: "Standard .npmrc configuration for pnpm strict mode",
    content: r"# GENERATED by guardrail3 — do not edit manually

# Peer dependencies — fail on missing or mismatched peers
strict-peer-dependencies=true

# Workspace safety — no circular deps between workspace packages
disallow-workspace-cycles=true

# Workspace protocol — `pnpm add` in workspace always writes workspace:* refs
save-workspace-protocol=rolling

# Engine enforcement — fail if a package needs a different Node version
engine-strict=true

# Exact pnpm version — everyone must use the version in packageManager field
package-manager-strict-version=true

# Build script security — fail if any dep runs install scripts not in onlyBuiltDependencies
strict-dep-builds=true

# Deps sync check — fail pnpm run/exec if node_modules doesn't match lockfile
verify-deps-before-run=error

# Supply chain — block packages published less than 24h ago
minimum-release-age=1440

# Supply chain — block transitive deps from using git repos or tarball URLs
block-exotic-subdeps=true

# Supply chain — warn if a package lost its npm provenance signatures
trust-policy=warn

# Version pinning — `pnpm add` writes exact versions, no ^ or ~
save-prefix=

# Hoisting — explicit about defaults
public-hoist-pattern=
shamefully-hoist=false
",
};

pub const TSCONFIG_BASE: Module = Module {
    name: "canonical/tsconfig-base",
    description: "Standard tsconfig.base.json configuration",
    content: r#"{
  "$schema": "https://json.schemastore.org/tsconfig",
  "_comment": "GENERATED by guardrail3 — do not edit manually",
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitOverride": true,
    "noFallthroughCasesInSwitch": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "noEmit": true
  }
}
"#,
};

pub const JSCPD: Module = Module {
    name: "canonical/jscpd",
    description: "Standard .jscpd.json copy-paste detection configuration",
    content: r#"{
  "$schema": "https://json.schemastore.org/jscpd.json",
  "_comment": "GENERATED by guardrail3 — do not edit manually",
  "threshold": 0,
  "minTokens": 50,
  "reporters": ["consoleFull"],
  "ignore": [
    "**/node_modules/**",
    "**/.next/**",
    "**/dist/**",
    "**/target/**",
    "**/components/ui/**",
    "**/components/pro-blocks/**",
    "**/drizzle/**",
    "**/__tests__/**",
    "**/__mocks__/**",
    "**/test/**",
    "**/*.generated.*",
    "**/coverage/**",
    "**/.plans/**",
    "**/.worklogs/**",
    "**/lib/utils.ts",
    "**/.claude/**",
    "**/test-data/**",
    "**/golden/**"
  ],
  "absolute": true,
  "format": ["typescript", "rust"]
}
"#,
};

pub const ESLINT_STARTER: Module = Module {
    name: "canonical/eslint-starter",
    description: "Starter eslint.config.mjs with core guardrail rules",
    content: r#"// GENERATED by guardrail3 — do not edit manually
// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
  },
  {
    // Global ignores
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/target/**",
      "**/drizzle/**",
      "**/*.generated.*",
    ],
  },
  {
    rules: {
      // --- Size guards ---
      "max-lines": ["error", { max: 400, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["warn", { max: 100, skipBlankLines: true, skipComments: true }],
      complexity: ["warn", 25],

      // --- Output discipline ---
      "no-console": ["error", { allow: ["warn", "error"] }],

      // --- Equality ---
      eqeqeq: ["error", "always"],

      // --- Banned packages ---
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "axios", message: "Use fetch instead" },
            { name: "lodash", message: "Use native JS methods" },
            { name: "moment", message: "Use date-fns or Temporal" },
            { name: "uuid", message: "Use crypto.randomUUID()" },
            { name: "nanoid", message: "Use crypto.randomUUID()" },
            { name: "pg", message: "Use drizzle-orm with postgres.js" },
            { name: "express", message: "Use Next.js API routes" },
            { name: "classnames", message: "Use cn() from @/lib/utils" },
            { name: "winston", message: "Use console or pino" },
            { name: "request", message: "Use fetch instead" },
            { name: "got", message: "Use fetch instead" },
            { name: "superagent", message: "Use fetch instead" },
            { name: "node-fetch", message: "Use native fetch" },
            { name: "isomorphic-fetch", message: "Use native fetch" },
            { name: "underscore", message: "Use native JS methods" },
            { name: "xregexp", message: "Use structured parsers (tree-sitter, AST) instead of regex" },
            { name: "regexp-tree", message: "Use structured parsers (tree-sitter, AST) instead of regex" },
          ],
        },
      ],

      // --- Globals ban ---
      "no-restricted-globals": [
        "error",
        {
          name: "process",
          message: "Use env() from @/lib/env instead of process.env",
        },
        {
          name: "RegExp",
          message: "Use Zod schemas for validation, structured parsers for parsing — never regex",
        },
      ],

      // --- Regex ban (AST-level) ---
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[regex]",
          message: "Regex literals are banned — use Zod schemas for validation, structured parsers for parsing",
        },
      ],

      // --- TypeScript strict rules ---
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/strict-boolean-expressions": "warn",
      "@typescript-eslint/explicit-function-return-type": [
        "warn",
        { allowExpressions: true, allowTypedFunctionExpressions: true },
      ],
    },
  },
);
"#,
};
