use super::Module;

const STYLELINT_CONFIG: &str = r#"// GENERATED by guardrail3 — do not edit manually
/** @type {import("stylelint").Config} */
export default {
  extends: ["stylelint-config-standard", "stylelint-config-tailwindcss"],
  plugins: ["@double-great/stylelint-a11y"],
  rules: {
    "a11y/content-property-no-static-value": true,
    "a11y/font-size-is-readable": true,
    "a11y/line-height-is-vertical-rhythmed": true,
    "a11y/media-prefers-reduced-motion": true,
    "a11y/no-display-none": true,
    "a11y/no-obsolete-attribute": true,
    "a11y/no-obsolete-element": true,
    "a11y/no-outline-none": true,
    "a11y/no-spread-text": true,
    "a11y/no-text-align-justify": true,
    "a11y/selector-pseudo-class-focus": true,
    "a11y/media-prefers-color-scheme": null,
    "no-duplicate-selectors": null,
  },
};
"#;

pub const STYLELINT: Module = Module {
    name: "canonical/stylelint",
    description: "Standard .stylelintrc.mjs configuration with accessibility rules for content apps",
    content: STYLELINT_CONFIG,
};

/// Build a .stylelintrc.mjs config for content apps with accessibility rules.
pub fn build_stylelint_config() -> String {
    STYLELINT_CONFIG.to_owned()
}
