[[ignore]]
fingerprint = "19666e012f4b095d"
reason = "test"

[[ignore]]
fingerprint = "ebca207f47110b29"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "d32bab7ac5670c75"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "bd9829318a31a3d7"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "5a442887ad6a9152"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "807436069e73de8e"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "8c15da0d7663bf60"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "95b5463e45877d8b"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "a130420960f89a32"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "d92ca0ad6917e49b"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "f7381995e4fe03a6"
reason = "Pre-existing structural similarity"

[[ignore]]
fingerprint = "fe3d2160548c918c"
reason = "Pre-existing structural similarity"
