mod always_true_cfg_attr_bypass;
mod cfg_attr_allow_inventory;
mod crate_level_allow;
mod deny_forbid_without_reason;
mod direct_fs_usage;
mod extern_allow;
mod fs_glob_import;
mod garde_skip_with_comment;
mod garde_skip_without_comment;
mod generic_parameter_cap;
mod impl_allow_blast_radius;
mod include_bypass;
mod input_failures;
mod item_level_allow_with_reason;
mod item_level_allow_without_reason;
mod large_trait_surface;
mod large_type_inventory;
mod many_use_imports;
mod panic_macro;
mod parse;
mod path_attr_with_reason;
mod public_struct_named_fields;
mod public_weak_error_forms;
mod run;
mod string_dispatch_cap;
mod support;
mod test_expect_message_quality;
mod todo_macros;
mod too_many_effective_code_lines;
mod too_many_use_imports;
mod unused_crate_dependencies_allow;

#[cfg(feature = "checks")]
pub use run::check;
