mod rs_clippy_02_max_struct_bools;
mod rs_clippy_03_max_fn_params_bools;
mod rs_clippy_09_too_many_lines_threshold;
mod rs_clippy_10_too_many_arguments_threshold;
mod rs_clippy_11_excessive_nesting_threshold;
mod rs_clippy_17_test_relaxations;
mod rs_clippy_21_cognitive_complexity_threshold;
mod rs_clippy_22_type_complexity_threshold;
mod run;
mod support;

pub use run::check;
